/**
 * Arkadia Distribution Module — /distribute
 * Sovereign music distribution: upload → covenant → submit → aggregator.
 * Artist retains 100% masters. Arkadia takes 5% capped fee.
 */
import React, { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../contexts/AuthContext';

const API_BASE = (import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/$/, '');

const C = {
  bg:     '#0A0A0F',
  panel:  'rgba(13,13,26,0.75)',
  border: 'rgba(201,168,76,0.12)',
  teal:   '#00D4AA',
  gold:   '#C9A84C',
  text:   'rgba(232,232,232,0.85)',
  muted:  'rgba(232,232,232,0.5)',
  dim:    'rgba(232,232,232,0.28)',
  red:    '#EF6C6C',
};

const GENRES = [
  'Afrobeats', 'Afrofusion', 'Afropop', 'Highlife', 'Jùjú', 'Fuji',
  'Amapiano', 'Afro-Soul', 'R&B', 'Hip-Hop', 'Gospel', 'Jazz', 'Electronic', 'Other',
];

const STATUS_COLORS: Record<string, string> = {
  draft:      C.dim,
  submitted:  C.gold,
  processing: C.teal,
  live:       '#4CAF50',
  failed:     C.red,
};

type Step = 1 | 2 | 3 | 4 | 5;

interface Metadata {
  title: string;
  artistName: string;
  featuring: string;
  genre: string;
  releaseDate: string;
  isrc: string;
  upc: string;
}

const COVENANT_TEXT = `ARKADIA DISTRIBUTION COVENANT

You retain 100% ownership of your masters and publishing.

Arkadia distributes your work through its pipeline to Spotify, Apple Music, Boomplay, and other major streaming platforms.

Arkadia receives 5% of streaming revenue generated by this release, capped at $500 USD (or equivalent in your local currency). This fee is collected only after you are paid by the aggregator.

You may leave the Arkadia distribution network at any time. No exit fees. No lock-in. Your masters leave with you.

This covenant is binding and witnessed by the Arkadia mesh. It is stored permanently in the IMS archive.

By signing below, you affirm that you own or control all rights to the work being submitted.`;

function DropZone({
  label, accept, hint, file, onFile, icon,
}: {
  label: string;
  accept: string;
  hint: string;
  file: File | null;
  onFile: (f: File) => void;
  icon: string;
}) {
  const ref = useRef<HTMLInputElement>(null);
  const [over, setOver] = useState(false);

  const onDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setOver(false);
    const f = e.dataTransfer.files[0];
    if (f) onFile(f);
  }, [onFile]);

  return (
    <div
      onDragOver={e => { e.preventDefault(); setOver(true); }}
      onDragLeave={() => setOver(false)}
      onDrop={onDrop}
      onClick={() => ref.current?.click()}
      style={{
        border: `2px dashed ${over ? C.teal : file ? C.gold : 'rgba(201,168,76,0.25)'}`,
        borderRadius: 14,
        padding: '28px 20px',
        textAlign: 'center',
        cursor: 'pointer',
        background: over ? 'rgba(0,212,170,0.04)' : file ? 'rgba(201,168,76,0.04)' : 'rgba(255,255,255,0.01)',
        transition: 'all 0.2s',
      }}
    >
      <input ref={ref} type="file" accept={accept} style={{ display: 'none' }}
        onChange={e => { const f = e.target.files?.[0]; if (f) onFile(f); }} />
      <div style={{ fontSize: 28, marginBottom: 10 }}>{file ? '✓' : icon}</div>
      <p style={{ fontFamily: 'sans-serif', fontSize: 12, color: file ? C.gold : C.muted, margin: '0 0 4px', letterSpacing: '0.06em' }}>
        {file ? file.name : label}
      </p>
      <p style={{ fontFamily: 'sans-serif', fontSize: 10, color: C.dim, margin: 0 }}>{hint}</p>
    </div>
  );
}

function StepIndicator({ step, total }: { step: Step; total: number }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 6, justifyContent: 'center', marginBottom: 28 }}>
      {Array.from({ length: total }, (_, i) => {
        const n = (i + 1) as Step;
        const done = step > n;
        const active = step === n;
        return (
          <React.Fragment key={n}>
            <motion.div
              animate={{ scale: active ? 1.1 : 1 }}
              style={{
                width: 28, height: 28, borderRadius: '50%',
                background: done ? C.teal : active ? 'rgba(0,212,170,0.15)' : 'rgba(255,255,255,0.04)',
                border: `1px solid ${done ? C.teal : active ? C.teal : 'rgba(255,255,255,0.1)'}`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontFamily: 'sans-serif', fontSize: 10, color: done ? '#0A0A0F' : active ? C.teal : C.dim,
                fontWeight: 600,
              }}
            >
              {done ? '✓' : n}
            </motion.div>
            {i < total - 1 && (
              <div style={{ width: 20, height: 1, background: step > n ? C.teal : 'rgba(255,255,255,0.08)' }} />
            )}
          </React.Fragment>
        );
      })}
    </div>
  );
}

const STEP_LABELS: Record<Step, string> = {
  1: 'Upload Audio',
  2: 'Upload Artwork',
  3: 'Metadata',
  4: 'Covenant',
  5: 'Submit',
};

export default function DistributePage() {
  const { user, isAuthenticated } = useAuth();

  const [step, setStep] = useState<Step>(1);
  const [audio, setAudio] = useState<File | null>(null);
  const [artwork, setArtwork] = useState<File | null>(null);
  const [meta, setMeta] = useState<Metadata>({
    title: '', artistName: '', featuring: '', genre: GENRES[0],
    releaseDate: '', isrc: '', upc: '',
  });
  const [covenantAgreed, setCovenantAgreed] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [releaseId, setReleaseId] = useState<string | null>(null);
  const [covenantId, setCovenantId] = useState<string | null>(null);
  const [progressLabel, setProgressLabel] = useState('');
  const [done, setDone] = useState(false);
  const [aggResponse, setAggResponse] = useState<Record<string, unknown> | null>(null);

  const headers = (): Record<string, string> => {
    if (user?.idToken) return { Authorization: `Bearer ${user.idToken}` };
    return {};
  };

  const setMetaField = (k: keyof Metadata, v: string) =>
    setMeta(prev => ({ ...prev, [k]: v }));

  const validate = (): string | null => {
    if (step === 1 && !audio) return 'Please upload an audio file.';
    if (step === 2 && !artwork) return 'Please upload artwork.';
    if (step === 3) {
      if (!meta.title.trim()) return 'Title is required.';
      if (!meta.artistName.trim()) return 'Artist name is required.';
      if (!meta.genre) return 'Genre is required.';
    }
    if (step === 4 && !covenantAgreed) return 'You must agree to the covenant before continuing.';
    return null;
  };

  const uploadAndSign = async () => {
    setError(null);
    setLoading(true);
    try {
      // Step 1: Upload files + metadata
      setProgressLabel('Uploading files…');
      const form = new FormData();
      form.append('audio', audio!);
      form.append('artwork', artwork!);
      form.append('title', meta.title);
      form.append('artistName', meta.artistName);
      form.append('featuring', meta.featuring);
      form.append('genre', meta.genre);
      form.append('releaseDate', meta.releaseDate);
      form.append('isrc', meta.isrc);
      form.append('upc', meta.upc);

      const uploadRes = await fetch(`${API_BASE}/api/distribution/upload`, {
        method: 'POST',
        headers: headers(),
        body: form,
      });
      if (!uploadRes.ok) {
        const err = await uploadRes.json().catch(() => ({ detail: uploadRes.statusText }));
        throw new Error(err.detail || 'Upload failed');
      }
      const uploadData = await uploadRes.json();
      const rid = uploadData.releaseId;
      setReleaseId(rid);

      // Step 2: Sign covenant
      setProgressLabel('Signing covenant…');
      const artistId = user?.uid || meta.artistName.toLowerCase().replace(/\s+/g, '_');
      const covenantRes = await fetch(`${API_BASE}/api/distribution/covenant/sign`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...headers() },
        body: JSON.stringify({ releaseId: rid, artistId, signedTerms: true }),
      });
      if (!covenantRes.ok) {
        const err = await covenantRes.json().catch(() => ({ detail: covenantRes.statusText }));
        throw new Error(err.detail || 'Covenant signing failed');
      }
      const covenantData = await covenantRes.json();
      setCovenantId(covenantData.covenantId);

      // Step 3: Submit to aggregator
      setProgressLabel('Submitting to aggregator…');
      const submitRes = await fetch(`${API_BASE}/api/distribution/submit`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...headers() },
        body: JSON.stringify({ releaseId: rid }),
      });
      if (!submitRes.ok) {
        const err = await submitRes.json().catch(() => ({ detail: submitRes.statusText }));
        throw new Error(err.detail || 'Submission failed');
      }
      const submitData = await submitRes.json();
      setAggResponse(submitData.aggregator || null);

      setProgressLabel('Done.');
      setDone(true);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'An error occurred. Please try again.');
    } finally {
      setLoading(false);
      setProgressLabel('');
    }
  };

  const handleNext = async () => {
    const err = validate();
    if (err) { setError(err); return; }
    setError(null);
    if (step < 5) {
      setStep((step + 1) as Step);
    } else {
      await uploadAndSign();
    }
  };

  const handleBack = () => {
    if (step > 1) setStep((step - 1) as Step);
    setError(null);
  };

  const inputStyle: React.CSSProperties = {
    background: 'rgba(0,0,0,0.3)',
    border: `1px solid rgba(201,168,76,0.2)`,
    color: C.text,
    borderRadius: 8,
    padding: '10px 12px',
    fontFamily: 'sans-serif',
    fontSize: 13,
    width: '100%',
    outline: 'none',
    boxSizing: 'border-box',
  };

  const labelStyle: React.CSSProperties = {
    fontFamily: 'sans-serif',
    fontSize: 9,
    letterSpacing: '0.3em',
    textTransform: 'uppercase',
    color: C.dim,
    marginBottom: 6,
    display: 'block',
  };

  if (done) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 14 }}
        animate={{ opacity: 1, y: 0 }}
        style={{ maxWidth: 480, margin: '0 auto', padding: '40px 16px', textAlign: 'center' }}
      >
        <motion.div
          animate={{ scale: [1, 1.08, 1], opacity: [0.7, 1, 0.7] }}
          transition={{ duration: 3, repeat: Infinity }}
          style={{ fontSize: 48, marginBottom: 20 }}
        >
          ☀️
        </motion.div>
        <h2 style={{ fontFamily: 'serif', fontSize: 24, color: C.teal, margin: '0 0 10px', letterSpacing: '0.08em' }}>
          Release Submitted
        </h2>
        <p style={{ fontFamily: 'sans-serif', fontSize: 13, color: C.muted, lineHeight: 1.7, margin: '0 0 20px' }}>
          Your release has been submitted to the Arkadia distribution pipeline.
          You will receive an email when it goes live on streaming platforms.
        </p>

        {releaseId && (
          <div style={{
            background: C.panel, border: `1px solid ${C.border}`, borderRadius: 12,
            padding: '16px 18px', marginBottom: 16, textAlign: 'left',
          }}>
            <p style={{ ...labelStyle, marginBottom: 10 }}>Release Details</p>
            <p style={{ fontFamily: 'sans-serif', fontSize: 11, color: C.muted, margin: '0 0 4px' }}>
              <span style={{ color: C.dim }}>ID · </span>{releaseId}
            </p>
            {covenantId && (
              <p style={{ fontFamily: 'sans-serif', fontSize: 11, color: C.muted, margin: '0 0 4px' }}>
                <span style={{ color: C.dim }}>Covenant · </span>{covenantId}
              </p>
            )}
            {aggResponse && typeof aggResponse === 'object' && 'referenceId' in aggResponse && (
              <p style={{ fontFamily: 'sans-serif', fontSize: 11, color: C.muted, margin: 0 }}>
                <span style={{ color: C.dim }}>Aggregator Ref · </span>{String(aggResponse.referenceId)}
              </p>
            )}
          </div>
        )}

        <div style={{
          background: 'rgba(0,212,170,0.04)', border: `1px solid rgba(0,212,170,0.15)`,
          borderRadius: 10, padding: '14px 16px', marginBottom: 20, textAlign: 'left',
        }}>
          <p style={{ fontFamily: 'sans-serif', fontSize: 11, color: 'rgba(0,212,170,0.7)', margin: 0, lineHeight: 1.6 }}>
            ⟐ Your masters are yours. The covenant is sealed in the IMS archive.
            The aggregator pipeline is active. The Return is now.
          </p>
        </div>

        <button
          onClick={() => {
            setDone(false); setStep(1); setAudio(null); setArtwork(null);
            setMeta({ title: '', artistName: '', featuring: '', genre: GENRES[0], releaseDate: '', isrc: '', upc: '' });
            setCovenantAgreed(false); setReleaseId(null); setCovenantId(null); setAggResponse(null);
          }}
          style={{
            padding: '12px 24px',
            background: 'rgba(201,168,76,0.08)', border: `1px solid rgba(201,168,76,0.3)`,
            borderRadius: 9, color: C.gold,
            fontFamily: 'sans-serif', fontSize: 10, letterSpacing: '0.22em',
            textTransform: 'uppercase', cursor: 'pointer',
          }}
        >
          ← Submit Another Release
        </button>
      </motion.div>
    );
  }

  return (
    <div style={{ maxWidth: 520, margin: '0 auto', padding: '8px 16px 60px' }}>

      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} style={{ marginBottom: 28, textAlign: 'center' }}>
        <p style={{ fontFamily: 'sans-serif', fontSize: 8, letterSpacing: '0.38em', textTransform: 'uppercase', color: 'rgba(201,168,76,0.4)', margin: '0 0 6px' }}>
          Sovereign Distribution
        </p>
        <h1 style={{ fontFamily: 'serif', fontSize: 26, color: C.teal, margin: '0 0 6px', letterSpacing: '0.08em' }}>
          Distribute
        </h1>
        <p style={{ fontFamily: 'sans-serif', fontSize: 11, color: C.dim, margin: 0, lineHeight: 1.6 }}>
          Upload your music. Sign the covenant. Reach every platform.
        </p>
      </motion.div>

      {/* Step indicator */}
      <StepIndicator step={step} total={5} />

      {/* Step label */}
      <p style={{ fontFamily: 'sans-serif', fontSize: 9, letterSpacing: '0.3em', textTransform: 'uppercase', color: C.gold, textAlign: 'center', marginBottom: 20 }}>
        Step {step} of 5 — {STEP_LABELS[step]}
      </p>

      {/* Step content */}
      <AnimatePresence mode="wait">
        <motion.div
          key={step}
          initial={{ opacity: 0, x: 12 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -12 }}
          transition={{ duration: 0.22 }}
        >

          {/* Step 1: Audio Upload */}
          {step === 1 && (
            <div>
              <DropZone
                label="Drop audio file here or click to browse"
                accept="audio/mpeg,audio/wav,audio/flac,.mp3,.wav,.flac"
                hint="MP3 · WAV · FLAC — 320kbps or lossless recommended"
                file={audio}
                onFile={setAudio}
                icon="🎵"
              />
              {audio && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                  style={{ marginTop: 12, padding: '10px 14px', background: 'rgba(0,212,170,0.05)', border: '1px solid rgba(0,212,170,0.15)', borderRadius: 8 }}>
                  <p style={{ fontFamily: 'sans-serif', fontSize: 11, color: C.teal, margin: 0 }}>
                    ✓ {audio.name} · {(audio.size / 1024 / 1024).toFixed(2)} MB
                  </p>
                </motion.div>
              )}
            </div>
          )}

          {/* Step 2: Artwork Upload */}
          {step === 2 && (
            <div>
              <DropZone
                label="Drop artwork here or click to browse"
                accept="image/jpeg,image/png,.jpg,.jpeg,.png"
                hint="JPEG or PNG · Minimum 2000×2000px recommended · Square format"
                file={artwork}
                onFile={setArtwork}
                icon="🖼"
              />
              {artwork && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                  style={{ marginTop: 12 }}>
                  <img
                    src={URL.createObjectURL(artwork)}
                    alt="Artwork preview"
                    style={{ width: '100%', maxWidth: 200, aspectRatio: '1', objectFit: 'cover', borderRadius: 10, border: `1px solid rgba(201,168,76,0.2)`, display: 'block', margin: '0 auto' }}
                  />
                </motion.div>
              )}
            </div>
          )}

          {/* Step 3: Metadata */}
          {step === 3 && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div>
                <label style={labelStyle}>Title *</label>
                <input style={inputStyle} value={meta.title} placeholder="Release title"
                  onChange={e => setMetaField('title', e.target.value)} />
              </div>
              <div>
                <label style={labelStyle}>Artist Name *</label>
                <input style={inputStyle} value={meta.artistName} placeholder="Your name or artist name"
                  onChange={e => setMetaField('artistName', e.target.value)} />
              </div>
              <div>
                <label style={labelStyle}>Featuring</label>
                <input style={inputStyle} value={meta.featuring} placeholder="ft. Artist (optional)"
                  onChange={e => setMetaField('featuring', e.target.value)} />
              </div>
              <div>
                <label style={labelStyle}>Genre *</label>
                <select style={{ ...inputStyle, appearance: 'none' }} value={meta.genre}
                  onChange={e => setMetaField('genre', e.target.value)}>
                  {GENRES.map(g => <option key={g} value={g}>{g}</option>)}
                </select>
              </div>
              <div>
                <label style={labelStyle}>Release Date</label>
                <input style={inputStyle} type="date" value={meta.releaseDate}
                  onChange={e => setMetaField('releaseDate', e.target.value)} />
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                <div>
                  <label style={labelStyle}>ISRC <span style={{ color: C.dim }}>(optional)</span></label>
                  <input style={inputStyle} value={meta.isrc} placeholder="Auto-generated"
                    onChange={e => setMetaField('isrc', e.target.value)} />
                </div>
                <div>
                  <label style={labelStyle}>UPC <span style={{ color: C.dim }}>(optional)</span></label>
                  <input style={inputStyle} value={meta.upc} placeholder="UPC code"
                    onChange={e => setMetaField('upc', e.target.value)} />
                </div>
              </div>
            </div>
          )}

          {/* Step 4: Covenant */}
          {step === 4 && (
            <div>
              <div style={{
                background: C.panel, border: `1px solid rgba(201,168,76,0.18)`,
                borderRadius: 12, padding: '18px 20px', maxHeight: 320, overflowY: 'auto',
                marginBottom: 20,
              }}>
                <pre style={{
                  fontFamily: 'sans-serif', fontSize: 12, color: C.muted, lineHeight: 1.8,
                  whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0,
                }}>
                  {COVENANT_TEXT}
                </pre>
              </div>
              <label style={{
                display: 'flex', alignItems: 'flex-start', gap: 12, cursor: 'pointer',
                padding: '14px 16px', background: covenantAgreed ? 'rgba(0,212,170,0.06)' : 'rgba(255,255,255,0.02)',
                border: `1px solid ${covenantAgreed ? 'rgba(0,212,170,0.3)' : 'rgba(255,255,255,0.07)'}`,
                borderRadius: 10, transition: 'all 0.2s',
              }}>
                <input
                  type="checkbox"
                  checked={covenantAgreed}
                  onChange={e => setCovenantAgreed(e.target.checked)}
                  style={{ marginTop: 2, accentColor: C.teal, width: 16, height: 16, flexShrink: 0 }}
                />
                <span style={{ fontFamily: 'sans-serif', fontSize: 12, color: covenantAgreed ? C.teal : C.muted, lineHeight: 1.6 }}>
                  I have read and agree to the Arkadia Distribution Covenant. I affirm that I own or control all rights to this work.
                </span>
              </label>
            </div>
          )}

          {/* Step 5: Review & Submit */}
          {step === 5 && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div style={{
                background: C.panel, border: `1px solid ${C.border}`, borderRadius: 12, padding: '16px 18px',
              }}>
                <p style={{ ...labelStyle, marginBottom: 12 }}>Release Summary</p>
                {artwork && (
                  <img src={URL.createObjectURL(artwork)} alt="artwork"
                    style={{ width: 72, height: 72, objectFit: 'cover', borderRadius: 8, marginBottom: 12, border: `1px solid rgba(201,168,76,0.2)` }} />
                )}
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {[
                    ['Title', meta.title],
                    ['Artist', meta.artistName],
                    meta.featuring && ['Featuring', meta.featuring],
                    ['Genre', meta.genre],
                    meta.releaseDate && ['Release Date', meta.releaseDate],
                    ['Audio', audio?.name || '—'],
                    ['Covenant', covenantAgreed ? '✓ Signed' : '✗ Not signed'],
                  ].filter(Boolean).map(([k, v]) => (
                    <div key={String(k)} style={{ display: 'flex', gap: 8 }}>
                      <span style={{ fontFamily: 'sans-serif', fontSize: 10, color: C.dim, letterSpacing: '0.12em', minWidth: 90 }}>{k}</span>
                      <span style={{ fontFamily: 'sans-serif', fontSize: 11, color: k === 'Covenant' && v === '✓ Signed' ? C.teal : C.muted }}>{String(v)}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div style={{
                background: 'rgba(201,168,76,0.04)', border: '1px solid rgba(201,168,76,0.12)',
                borderRadius: 10, padding: '12px 14px',
              }}>
                <p style={{ fontFamily: 'sans-serif', fontSize: 11, color: 'rgba(201,168,76,0.65)', margin: 0, lineHeight: 1.6 }}>
                  ✦ You own 100% of your masters. Arkadia takes 5% (capped at $500).
                  Payouts go directly to you from the aggregator.
                </p>
              </div>

              {/* Progress indicator */}
              {loading && (
                <motion.div
                  animate={{ opacity: [0.5, 1, 0.5] }}
                  transition={{ duration: 1.5, repeat: Infinity }}
                  style={{
                    padding: '12px 14px', background: 'rgba(0,212,170,0.05)',
                    border: '1px solid rgba(0,212,170,0.15)', borderRadius: 8,
                    fontFamily: 'sans-serif', fontSize: 11, color: C.teal,
                  }}
                >
                  ⟐ {progressLabel || 'Processing…'}
                </motion.div>
              )}
            </div>
          )}

        </motion.div>
      </AnimatePresence>

      {/* Error */}
      {error && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
          style={{
            marginTop: 16, padding: '10px 14px',
            background: 'rgba(239,108,108,0.06)', border: '1px solid rgba(239,108,108,0.3)',
            borderRadius: 8, fontFamily: 'sans-serif', fontSize: 12, color: C.red,
          }}
        >
          {error}
        </motion.div>
      )}

      {/* Navigation buttons */}
      <div style={{ display: 'flex', gap: 10, marginTop: 24 }}>
        {step > 1 && (
          <button onClick={handleBack} disabled={loading}
            style={{
              flex: 1, padding: '13px', background: 'rgba(255,255,255,0.03)',
              border: '1px solid rgba(255,255,255,0.08)', borderRadius: 10,
              color: C.dim, fontFamily: 'sans-serif', fontSize: 10,
              letterSpacing: '0.2em', textTransform: 'uppercase', cursor: loading ? 'not-allowed' : 'pointer',
            }}>
            ← Back
          </button>
        )}
        <button onClick={handleNext} disabled={loading}
          style={{
            flex: 2, padding: '13px',
            background: step === 5 ? 'rgba(0,212,170,0.12)' : 'rgba(201,168,76,0.10)',
            border: `1px solid ${step === 5 ? 'rgba(0,212,170,0.4)' : 'rgba(201,168,76,0.35)'}`,
            borderRadius: 10,
            color: step === 5 ? C.teal : C.gold,
            fontFamily: 'sans-serif', fontSize: 10,
            letterSpacing: '0.22em', textTransform: 'uppercase',
            cursor: loading ? 'not-allowed' : 'pointer', opacity: loading ? 0.6 : 1,
            transition: 'all 0.2s',
          }}>
          {loading ? `⟐ ${progressLabel || 'Processing…'}` : step === 5 ? '⟐ Submit Release' : 'Continue →'}
        </button>
      </div>

      {/* Auth nudge */}
      {!isAuthenticated && (
        <p style={{ fontFamily: 'sans-serif', fontSize: 10, color: C.dim, textAlign: 'center', marginTop: 16, lineHeight: 1.6 }}>
          You can distribute without an account, but logging in links releases to your node profile.
        </p>
      )}
    </div>
  );
}
