import React, { useEffect, useState } from 'react';
import { apiFetch } from '../lib/apiClient';
import { useAuth } from '../contexts/AuthContext';

const C = { panel:'rgba(16,18,31,.78)', border:'rgba(255,255,255,.07)', text:'#E9E7DF', gold:'#C9A84C', teal:'#00D4AA', blue:'#6A9FD8', dim:'rgba(233,231,223,.42)' };

type Overview = any;

function Status({label,value,kind='observed'}:{label:string;value:React.ReactNode;kind?:string}) { const tone=kind==='warning'||kind==='drift'?'#D98B5F':kind==='unknown'?'#9A9AA2':C.teal; return <div style={{border:`1px solid ${C.border}`,background:C.panel,borderRadius:14,padding:16}}><div style={{font:'8px ui-monospace,monospace',letterSpacing:'.16em',textTransform:'uppercase',color:`${tone}aa`}}>{kind}</div><div style={{marginTop:7,font:'600 22px ui-monospace,monospace',color:tone}}>{value}</div><div style={{marginTop:5,font:'9px ui-monospace,monospace',letterSpacing:'.12em',textTransform:'uppercase',color:C.dim}}>{label}</div></div> }
function Section({title,children}:{title:string;children:React.ReactNode}) { return <section style={{border:`1px solid ${C.border}`,background:'rgba(16,18,31,.66)',borderRadius:16,padding:18}}><div style={{font:'8px ui-monospace,monospace',letterSpacing:'.18em',textTransform:'uppercase',color:'rgba(201,168,76,.58)'}}>{title}</div>{children}</section> }

export default function EngineeringLabPage() {
  const { user } = useAuth();
  const [data,setData]=useState<Overview|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{let live=true;setLoading(true);setError(null);apiFetch('/api/lab/overview',{headers:{}}).then(async r=>{if(!r.ok)throw new Error(`${r.status}: ${(await r.text()).slice(0,180)}`);return r.json()}).then(x=>{if(live)setData(x)}).catch(e=>{if(live)setError(e.message||'Engineering Lab unavailable')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[user?.idToken]);
  if(loading) return <div style={{padding:24,color:C.dim,font:'12px Inter,system-ui'}}>Reconstructing Arkadia from repository evidence…</div>;
  if(error) return <div style={{padding:24,border:`1px solid ${C.border}`,borderRadius:16,color:'#D98B5F',background:C.panel}}><strong>Engineering Lab unavailable</strong><div style={{marginTop:7,fontSize:12}}>{error}</div></div>;
  if(!data) return null;
  const a=data.architecture||{}; const t=data.trajectory||{}; const c=data.canon||{}; const g=data.governance||{};
  return <div style={{display:'grid',gap:14}}>
    <header style={{border:`1px solid ${C.border}`,background:'radial-gradient(circle at 90% 0%,rgba(201,168,76,.13),transparent 44%),rgba(16,18,31,.82)',borderRadius:18,padding:'22px 20px'}}><div style={{font:'8px ui-monospace,monospace',letterSpacing:'.2em',textTransform:'uppercase',color:`${C.gold}99`}}>Arkadia AI Engineering Lab · v0.1</div><h1 style={{margin:'7px 0 5px',font:'400 31px Georgia,serif',color:C.text}}>See the system. Separate evidence from inference.</h1><p style={{margin:0,maxWidth:780,font:'12px/1.65 Inter,system-ui,sans-serif',color:C.dim}}>A deterministic observatory over the existing Arkadia substrate. No second kernel, provider, auth layer, persistence system or mutation loop is introduced.</p></header>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10}}><Status label="Repository" value={data.repository?.clean===true?'CLEAN':data.repository?.clean===false?'DIRTY':'UNKNOWN'} kind={data.repository?.clean==null?'unknown':'observed'}/><Status label="Modules" value={a.modules ?? 'UNKNOWN'}/><Status label="Routes" value={a.routes ?? 'UNKNOWN'}/><Status label="Execution paths" value={a.execution_paths ?? 'UNKNOWN'}/><Status label="Commits analysed" value={t.commits_analysed ?? 'UNKNOWN'}/><Status label="Patterns" value={data.patterns?.length ?? 'UNKNOWN'}/></div>
    <Section title="System status"><div style={{display:'grid',gap:7,marginTop:12,font:'11px/1.5 Inter,system-ui,sans-serif',color:C.dim}}><div><b style={{color:C.text}}>HEAD:</b> {data.repository?.head||'UNKNOWN'}</div><div><b style={{color:C.text}}>Branch:</b> {data.repository?.branch||'UNKNOWN'}</div><div><b style={{color:C.text}}>Observation:</b> {data.status||'UNKNOWN'}</div></div></Section>
    <Section title="Architecture"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr))',gap:9,marginTop:12}}>{[['components',a.components],['modules',a.modules],['services',a.services],['routes',a.routes],['execution paths',a.execution_paths]].map(([k,v])=><div key={String(k)} style={{padding:12,border:`1px solid ${C.border}`,borderRadius:10}}><div style={{font:'600 19px ui-monospace,monospace',color:C.blue}}>{v ?? 'UNKNOWN'}</div><div style={{marginTop:4,font:'8px ui-monospace,monospace',textTransform:'uppercase',color:C.dim}}>{k}</div></div>)}</div></Section>
    <Section title="Trajectory"><div style={{marginTop:12,font:'11px/1.6 Inter,system-ui,sans-serif',color:C.dim}}>{t.commits_analysed ?? 0} commits analysed · {t.high_churn_components ?? 0} high-churn components · {t.major_transitions ?? 0} bounded transitions.</div></Section>
    <Section title="Canon"><div style={{marginTop:12,font:'11px/1.6 Inter,system-ui,sans-serif',color:C.dim}}><b style={{color:c.loaded?C.teal:'#9A9AA2'}}>{c.loaded?'LOADED':'UNKNOWN'}</b> · {c.sources?.length ?? 0} repository sources. Canonical declarations remain distinct from derived implementation patterns.</div></Section>
    <Section title="Patterns"><div style={{display:'grid',gap:8,marginTop:12}}>{(data.patterns||[]).length ? data.patterns.map((p:any)=><div key={p.pattern_id} style={{padding:12,border:`1px solid ${C.border}`,borderRadius:10}}><div style={{font:'500 12px Inter,system-ui,sans-serif',color:C.text}}>{p.type}</div><div style={{marginTop:4,font:'9px ui-monospace,monospace',color:C.dim}}>{p.severity} · confidence {Math.round((p.confidence||0)*100)}% · {p.evidence?.length||0} evidence items</div></div>) : <div style={{color:C.dim,fontSize:11}}>No evidence-backed structural pattern detected in the current snapshot.</div>}</div></Section>
    <Section title="Governance"><div style={{marginTop:12,display:'flex',gap:10,flexWrap:'wrap',font:'9px ui-monospace,monospace',color:C.dim}}><span>AUTHORITY ≤ {g.maximum_authority ?? 'UNKNOWN'}</span><span>MUTATION {g.autonomous_mutation===false?'DISABLED':'UNKNOWN'}</span><span>PRODUCTION {g.production_mutation===false?'DISABLED':'UNKNOWN'}</span><span>APPROVAL {g.approval_required===true?'REQUIRED':'UNKNOWN'}</span></div></Section>
    {data.errors?.length>0&&<Section title="Observation errors"><div style={{marginTop:12,color:'#D98B5F',font:'10px/1.5 ui-monospace,monospace'}}>{data.errors.map((e:any,i:number)=><div key={i}>{e.component}: {e.status} · {e.reason}</div>)}</div></Section>}
  </div>;
}
