import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ApiError, apiFetch, apiRequest } from '../lib/apiClient';

type Project = { id:string; name:string; status:string; metadata?:Record<string,unknown> };
type Session = { session_id:string; workspace_ref:string; agent_id:string; state:string; objective:string; project_ref?:string|null; authorization_ref?:string|null; repository_ref?:string|null };
type Event = { event_id:string; event_type:string; sequence:number; timestamp_utc?:string; run_id?:string|null; payload?:Record<string,unknown> };
type Run = { run_id:string; state:string; result_state?:string|null; objective?:string };
type Result = { run_id?:string; state?:string; result_state?:string; loop_state?:string; summary?:string; turns?:Array<{text?:string;tool_name?:string|null;decision?:string;observation?:unknown}>; candidate_patch?:unknown };
type Tab = 'events'|'files'|'diff'|'evidence'|'artifacts'|'run';
const C={bg:'#080b10',panel:'#0d1219',panel2:'#101720',border:'rgba(255,255,255,.08)',strong:'rgba(0,212,170,.25)',text:'#e7edf3',muted:'#8491a0',dim:'#5e6a77',teal:'#00d4aa',gold:'#c9a84c',blue:'#79a9df',red:'#e06b72',purple:'#b08de8'};
const button=(c=C.teal):React.CSSProperties=>({border:'1px solid '+c+'55',background:c+'0d',color:c,borderRadius:7,padding:'8px 11px',font:'700 9px ui-monospace,SFMono-Regular,monospace',letterSpacing:'.08em',cursor:'pointer'});
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',background:'#080c11',color:C.text,border:'1px solid '+C.border,borderRadius:7,padding:'10px 11px',outline:'none',font:'12px Inter,system-ui,sans-serif'};
const short=(v?:string|null)=>v?(v.length>18?v.slice(0,8)+'…'+v.slice(-6):v):'—';
const human=(v?:unknown)=>String(v??'UNKNOWN').replace(/_/g,' ');
const tone=(v?:string)=>{const s=String(v||'').toUpperCase();if(['AUTHORIZED','RUNNING','VERIFYING','DONE','AVAILABLE'].includes(s))return C.teal;if(['BLOCKED','FAILED','UNAVAILABLE'].includes(s))return C.red;if(['PROPOSED','QUEUED','READY_FOR_REVIEW','CHECKPOINTED'].includes(s))return C.gold;return C.muted};
function Pill({value}:{value:string}){const c=tone(value);return <span style={{border:'1px solid '+c+'44',background:c+'10',color:c,borderRadius:99,padding:'4px 7px',font:'700 8px ui-monospace,SFMono-Regular,monospace'}}>{human(value)}</span>}
function Empty({title,detail}:{title:string;detail:string}){return <div style={{padding:25,textAlign:'center',color:C.muted,fontSize:10}}><strong style={{display:'block',color:'#aeb8c3',fontSize:12}}>{title}</strong><span style={{display:'block',marginTop:6,lineHeight:1.5}}>{detail}</span></div>}
async function req<T>(path:string,options:RequestInit={}){return apiRequest<T>(path,options)}
async function post<T>(path:string,body:unknown){return req<T>(path,{method:'POST',body:JSON.stringify(body)})}

export default function EngineeringLabPage(){
 const [projects,setProjects]=useState<Project[]>([]),[workspace,setWorkspace]=useState<any>(null),[sessions,setSessions]=useState<Session[]>([]);
 const [project,setProject]=useState<Project|null>(null),[session,setSession]=useState<Session|null>(null),[view,setView]=useState<any>(null),[events,setEvents]=useState<Event[]>([]);
 const [files,setFiles]=useState<any[]>([]),[file,setFile]=useState<any>(null),[tab,setTab]=useState<Tab>('events'),[objective,setObjective]=useState('Inspect the selected project and report its current engineering state.'),[provider,setProvider]=useState('ollama');
 const [result,setResult]=useState<Result|null>(null),[selectedRun,setSelectedRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState<unknown>(null),[notice,setNotice]=useState(''),[streaming,setStreaming]=useState(false);
 const poll=useRef<number|null>(null);
 const refresh=useCallback(async(id:string)=>{const d=await req<any>('/api/lab/engineering/sessions/'+encodeURIComponent(id));setView(d);setSession(d.session);setEvents(d.events||[]);return d},[]);
 const boot=useCallback(async()=>{const p=await req<{projects:Project[]}>('/solspire/projects');const w=await req<any>('/solspire/workspace');const s=await req<{sessions:Session[]}>('/api/lab/engineering/sessions');setProjects(p.projects||[]);setWorkspace(w.workspace);setSessions(s.sessions||[]);const saved=localStorage.getItem('arkadia.aeas01.project');const savedS=localStorage.getItem('arkadia.aeas01.session');const pr=(p.projects||[]).find(x=>x.id===saved)||(p.projects||[])[0]||null;setProject(pr);const se=(s.sessions||[]).find(x=>x.session_id===savedS)||(pr&&(s.sessions||[]).find(x=>x.project_ref===pr.id));if(se){setSession(se);await refresh(se.session_id)}},[refresh]);
 useEffect(()=>{boot().catch(setError);return()=>{if(poll.current)clearInterval(poll.current)}},[boot]);
 useEffect(()=>{if(!project){setFiles([]);return}req<any>('/solspire/projects/'+encodeURIComponent(project.id)+'/files').then(d=>setFiles(d.files||[])).catch(()=>setFiles([]))},[project]);
 useEffect(()=>{if(!session)return;let cancelled=false;let reader:ReadableStreamDefaultReader<Uint8Array>|undefined;const connect=async()=>{try{const response=await apiFetch('/api/lab/engineering/sessions/'+encodeURIComponent(session.session_id)+'/events');if(!response.ok||!response.body)throw new Error('event stream unavailable');setStreaming(true);reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';while(!cancelled){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\\n\\n');buffer=chunks.pop()||'';for(const chunk of chunks){const line=chunk.split('\\n').find(x=>x.startsWith('data: '));if(!line)continue;try{const event=JSON.parse(line.slice(6)) as Event;setEvents(prev=>prev.some(x=>x.event_id===event.event_id)?prev:[...prev,event].sort((a,b)=>a.sequence-b.sequence));}catch{}}}}catch(e){if(!cancelled)setNotice('Live event transport unavailable. Persisted events remain available.')}finally{if(!cancelled)setStreaming(false)}};void connect();return()=>{cancelled=true;void reader?.cancel()}},[session?.session_id]);
 const chooseProject=(p:Project)=>{setProject(p);setSession(null);setView(null);setResult(null);setNotice('');localStorage.setItem('arkadia.aeas01.project',p.id)};
 async function create(){if(!project||!workspace?.id||!objective.trim())return;setBusy(true);setError(null);try{const a=await post<any>('/api/lab/engineering/agents',{role:'WEAVER',display_name:project.name+' · Engineering Lab',capabilities:['READ','OBSERVE','PROPOSE'],write_allowed:false,model_ref:provider});const s=await post<Session>('/api/lab/engineering/sessions',{workspace_ref:workspace.id,agent_id:a.agent_id,objective:objective.trim(),project_ref:project.id});setSession(s);setView({session:s,events:[],runs:[],evidence:[],artifacts:[]});setEvents([]);setResult(null);localStorage.setItem('arkadia.aeas01.session',s.session_id);setSessions(x=>[s,...x]);setNotice('PROPOSED. Review the scope before granting human authorization.')}catch(e){setError(e)}finally{setBusy(false)}}
 async function authorize(){if(!session)return;setBusy(true);setError(null);try{const d=await post<any>('/api/lab/engineering/sessions/'+session.session_id+'/authorize',{operations_allowed:['read','list','git_status'],duration_minutes:30});setSession(d.session);await refresh(session.session_id);setNotice('AUTHORIZED for read, list and Git observation only. Mutation, commit, merge and deployment remain outside this surface.')}catch(e){setError(e)}finally{setBusy(false)}}
 async function run(){if(!session)return;setRunning(true);setError(null);setResult(null);setTab('run');setNotice('RUNNING. The browser request is asynchronous, so the interface remains usable.');if(poll.current)clearInterval(poll.current);poll.current=window.setInterval(()=>void refresh(session.session_id).catch(()=>{}),1400);try{const r=await post<Result>('/api/lab/engineering/sessions/'+session.session_id+'/run-agent',{objective:objective.trim(),provider,max_turns:8});setResult(r);await refresh(session.session_id);const s=await req<{sessions:Session[]}>('/api/lab/engineering/sessions');setSessions(s.sessions||[]);setNotice('Run returned. Review observations, evidence and artifacts. Execution is not verification or acceptance.')}catch(e){setError(e);await refresh(session.session_id).catch(()=>{})}finally{setRunning(false);if(poll.current){clearInterval(poll.current);poll.current=null}}}
 const runs:Run[]=view?.runs||[],evidence=view?.evidence||[],artifacts=view?.artifacts||[],turns=result?.turns||[],state=running?'RUNNING':session?.state||'NO SESSION';
 return <div data-testid='aeas-01-engineering-lab' style={{minHeight:'calc(100vh - 52px)',background:C.bg,color:C.text,fontFamily:'Inter,system-ui,sans-serif',display:'grid',gridTemplateRows:'50px 1fr',overflow:'hidden'}}>
  <header style={{display:'flex',alignItems:'center',gap:11,padding:'0 13px',borderBottom:'1px solid '+C.border,background:'#0a0e13',minWidth:0}}><div style={{display:'flex',gap:8,alignItems:'center',minWidth:180}}><span style={{width:7,height:7,borderRadius:99,background:C.teal,boxShadow:'0 0 12px '+C.teal+'88'}}/><b style={{font:'700 10px ui-monospace,monospace',letterSpacing:'.12em'}}>AEAS-01</b><span style={{color:C.dim,fontSize:9}}>ENGINEERING LAB</span></div><div style={{flex:1,minWidth:0,overflow:'hidden',whiteSpace:'nowrap',textOverflow:'ellipsis',fontSize:11}}><span style={{color:C.muted}}>PROJECT · </span><b>{project?.name||'None'}</b><span style={{color:C.dim}}> · </span><span style={{color:C.muted}}>{session?.repository_ref||'repository context'}</span></div><Pill value={state}/><span style={{color:streaming?C.teal:C.dim,font:'700 8px ui-monospace,monospace'}}>{streaming?'● LIVE':'○ EVENT LOG'}</span><button style={button(C.blue)} disabled={busy||running} onClick={()=>void boot()}>REFRESH</button></header>
  <div style={{minHeight:0,display:'grid',gridTemplateColumns:'225px minmax(0,1fr) 325px'}}>
   <aside style={{minHeight:0,overflowY:'auto',borderRight:'1px solid '+C.border,background:'#0a0f15'}}><div style={{padding:12,borderBottom:'1px solid '+C.border}}><div style={{color:C.gold,font:'700 8px ui-monospace,monospace',letterSpacing:'.14em'}}>WORKSPACE</div><div style={{marginTop:5,color:C.muted,fontSize:9}}>{workspace?.id?'Bound · '+short(workspace.id):'Canonical workspace unavailable'}</div></div>
    <div style={{padding:8}}><div style={{padding:6,color:C.dim,font:'700 8px ui-monospace,monospace'}}>PROJECTS</div>{projects.map(p=><button key={p.id} onClick={()=>chooseProject(p)} style={{width:'100%',textAlign:'left',border:'1px solid '+(project?.id===p.id?C.strong:'transparent'),background:project?.id===p.id?'rgba(0,212,170,.05)':'transparent',color:C.text,borderRadius:7,padding:8,cursor:'pointer',marginBottom:3}}><b style={{display:'block',fontSize:10,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.name}</b><small style={{color:C.dim}}>{p.status}</small></button>)}{!projects.length&&<Empty title='No projects' detail='A project context is required.'/>}</div>
    <div style={{padding:8,borderTop:'1px solid '+C.border}}><div style={{padding:6,color:C.dim,font:'700 8px ui-monospace,monospace'}}>SESSIONS</div>{sessions.slice(0,15).map(s=><button key={s.session_id} onClick={()=>{setSession(s);localStorage.setItem('arkadia.aeas01.session',s.session_id);void refresh(s.session_id)}} style={{width:'100%',textAlign:'left',border:'1px solid '+(session?.session_id===s.session_id?C.strong:'transparent'),background:session?.session_id===s.session_id?'rgba(0,212,170,.05)':'transparent',color:C.text,borderRadius:7,padding:7,cursor:'pointer',marginBottom:3}}><div style={{display:'flex',justifyContent:'space-between',gap:4}}><span style={{color:C.blue,font:'8px ui-monospace,monospace'}}>{short(s.session_id)}</span><Pill value={s.state}/></div><div style={{marginTop:4,color:C.muted,fontSize:9,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{s.objective||'No objective'}</div></button>)}</div>
   </aside>
   <main style={{minWidth:0,minHeight:0,display:'grid',gridTemplateRows:'auto 1fr auto',background:'#0b1016'}}><div style={{padding:'11px 15px',borderBottom:'1px solid '+C.border,display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{color:C.dim,font:'700 8px ui-monospace,monospace',letterSpacing:'.13em'}}>OPERATOR CONVERSATION</div><div style={{marginTop:4,color:C.muted,fontSize:10}}>{session?'Session '+short(session.session_id)+' · Agent '+short(session.agent_id):'Select a project and create a bounded session'}</div></div>{session&&<span style={{color:C.dim,font:'8px ui-monospace,monospace'}}>ACCESS ≠ AUTHORIZATION</span>}</div>
    <div style={{minHeight:0,overflowY:'auto',padding:15}}>{!session?<section style={{maxWidth:700,margin:'7vh auto'}}><div style={{color:C.teal,font:'700 8px ui-monospace,monospace',letterSpacing:'.16em'}}>NATIVE OPERATOR SURFACE</div><h1 style={{fontSize:28,margin:'8px 0'}}>Operate the system, not the dashboard.</h1><p style={{color:C.muted,fontSize:12,lineHeight:1.7}}>This surface sits over Arkadia's existing Lab runtime, project store, event stream, evidence records and authorization boundary. It does not create a parallel engineering system.</p></section>:<div style={{display:'grid',gap:9,maxWidth:900,margin:'0 auto'}}>{!events.length&&!turns.length&&!result&&<div style={{padding:16,border:'1px dashed '+C.border,borderRadius:8,color:C.muted,fontSize:10}}>No runtime activity yet. The next transition is explicit authorization.</div>}{events.map(e=><article key={e.event_id} style={{padding:10,border:'1px solid '+C.border,background:C.panel,borderRadius:8}}><div style={{display:'flex',justifyContent:'space-between'}}><b style={{color:C.teal,fontSize:9}}>#{e.sequence} · {human(e.event_type)}</b><span style={{color:C.dim,fontSize:8}}>{e.timestamp_utc?new Date(e.timestamp_utc).toLocaleTimeString():''}</span></div><pre style={{margin:'7px 0 0',whiteSpace:'pre-wrap',overflowWrap:'anywhere',color:C.muted,font:'9px/1.5 ui-monospace,monospace'}}>{JSON.stringify(e.payload||{},null,2)}</pre></article>)}
      {turns.map((t,i)=><article key={i} style={{border:'1px solid '+C.border,background:C.panel2,borderRadius:8,overflow:'hidden'}}><div style={{padding:'7px 9px',borderBottom:'1px solid '+C.border,display:'flex',justifyContent:'space-between'}}><b style={{color:C.gold,font:'8px ui-monospace,monospace'}}>TURN {i+1}</b><Pill value={t.decision||t.tool_name||'OBSERVED'}/></div><div style={{padding:10}}>{t.text&&<p style={{margin:0,fontSize:11,lineHeight:1.65,whiteSpace:'pre-wrap'}}>{t.text}</p>}{t.observation&&<details style={{marginTop:7}}><summary style={{color:C.muted,fontSize:9,cursor:'pointer'}}>Tool observation</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',color:C.muted,font:'9px/1.5 ui-monospace,monospace'}}>{JSON.stringify(t.observation,null,2)}</pre></details>}</div></article>)}
      {result?.summary&&<article style={{padding:12,border:'1px solid '+C.strong,background:'rgba(0,212,170,.035)',borderRadius:8}}><b style={{color:C.teal,font:'8px ui-monospace,monospace'}}>RUN RESULT</b><p style={{fontSize:11,lineHeight:1.6}}>{result.summary}</p></article>}</div>}</div>
    <div style={{borderTop:'1px solid '+C.border,padding:11,background:'#0a0f14'}}><div style={{display:'flex',gap:7,alignItems:'flex-end'}}><textarea aria-label='Engineering objective' value={objective} disabled={!!session||running} onChange={e=>setObjective(e.target.value)} rows={3} placeholder='Describe the engineering work…' style={{...input,resize:'vertical',flex:1}}/><div style={{width:145,display:'grid',gap:6}}><select aria-label='Model provider' value={provider} disabled={!!session||running} onChange={e=>setProvider(e.target.value)} style={input}><option value='ollama'>Ollama</option><option value='gemini'>Gemini</option><option value='openai_compatible'>OpenAI compatible</option></select>{!session?<button disabled={busy||!project||!objective.trim()} onClick={()=>void create()} style={button()}>{busy?'CREATING…':'CREATE SESSION'}</button>:session.state==='PROPOSED'?<button disabled={busy} onClick={()=>void authorize()} style={button(C.gold)}>{busy?'AUTHORIZING…':'AUTHORIZE'}</button>:<button disabled={busy||running} onClick={()=>void run()} style={button()}>{running?'RUNNING…':'RUN AGENT'}</button>}</div></div><div style={{marginTop:6,color:C.dim,font:'8px ui-monospace,monospace'}}>{notice||'Execution ≠ verification · verification ≠ acceptance'}{running&&<span style={{color:C.gold,marginLeft:10}}>ASYNC REQUEST ACTIVE · UI UNLOCKED</span>}</div>{error&&<div role='alert' style={{marginTop:7,color:'#ffb7bc',fontSize:9}}>{error instanceof ApiError?error.kind+': '+error.message:String(error)}</div>}</div></main>
   <aside style={{minHeight:0,overflowY:'auto',borderLeft:'1px solid '+C.border,background:'#0a0f15'}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',borderBottom:'1px solid '+C.border}}>{(['events','files','diff','evidence','artifacts','run'] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} style={{border:0,borderBottom:tab===t?'2px solid '+C.teal:'2px solid transparent',background:tab===t?'rgba(0,212,170,.05)':'transparent',color:tab===t?C.teal:C.muted,padding:8,cursor:'pointer',font:'700 7px ui-monospace,monospace'}}>{t.toUpperCase()}</button>)}</div><div style={{padding:10}}>
    {tab==='events'&&(events.length?events.slice().reverse().map(e=><button key={e.event_id} onClick={()=>setSelectedRun(runs.find(r=>r.run_id===e.run_id)||null)} style={{width:'100%',textAlign:'left',padding:8,marginBottom:5,border:'1px solid '+C.border,background:C.panel,color:C.text,borderRadius:7,cursor:'pointer'}}><b style={{color:C.teal,fontSize:9}}>{human(e.event_type)}</b><div style={{color:C.dim,fontSize:8,marginTop:3}}>#{e.sequence} · {short(e.run_id)}</div></button>):<Empty title='No events' detail='Native runtime events appear here.'/>) }
    {tab==='files'&&(files.length?files.map(f=><button key={f.id||f.name} onClick={()=>setFile(f)} style={{width:'100%',textAlign:'left',padding:8,marginBottom:5,border:'1px solid '+(file?.id===f.id?C.strong:C.border),background:C.panel,color:C.text,borderRadius:7,cursor:'pointer'}}><div style={{font:'9px ui-monospace,monospace',overflowWrap:'anywhere'}}>{f.name}</div><small style={{color:C.dim}}>{f.mime_type||'text'} · {f.size||0} bytes</small></button>):<Empty title='No files returned' detail='The project file API did not expose a file corpus.'/>) }{file?.content!==undefined&&<pre style={{maxHeight:430,overflow:'auto',whiteSpace:'pre-wrap',color:C.muted,font:'8px/1.5 ui-monospace,monospace',background:'#070a0e',padding:9}}>{file.content}</pre>}</div>
    {tab==='diff'&&(result?.candidate_patch?<pre style={{maxHeight:600,overflow:'auto',whiteSpace:'pre-wrap',overflowWrap:'anywhere',color:C.muted,font:'8px/1.5 ui-monospace,monospace'}}>{JSON.stringify(result.candidate_patch,null,2)}</pre>:<Empty title='No candidate diff' detail='The current Lab run has not returned a candidate patch.'/>) }
    {tab==='evidence'&&(evidence.length?evidence.map((e:any)=><article key={e.evidence_id} style={{padding:9,border:'1px solid '+C.border,background:C.panel,borderRadius:7,marginBottom:5}}><div style={{display:'flex',justifyContent:'space-between'}}><b style={{color:C.gold,fontSize:8}}>{short(e.evidence_id)}</b><Pill value={e.state}/></div><p style={{color:C.muted,fontSize:9,lineHeight:1.5}}>{e.summary}</p><details><summary style={{color:C.dim,fontSize:8}}>detail / provenance</summary><pre style={{whiteSpace:'pre-wrap',color:C.dim,font:'7px/1.4 ui-monospace,monospace'}}>{JSON.stringify({detail:e.detail,provenance:e.provenance},null,2)}</pre></details></article>):<Empty title='No evidence' detail='Evidence is emitted by the runtime, not fabricated by the UI.'/>) }
    {tab==='artifacts'&&(artifacts.length?artifacts.map((a:any)=><article key={a.artifact_id} style={{padding:9,border:'1px solid '+C.border,background:C.panel,borderRadius:7,marginBottom:5}}><b style={{color:C.purple,fontSize:8}}>{human(a.kind)}</b><div style={{fontSize:9,marginTop:4}}>{a.title}</div><pre style={{whiteSpace:'pre-wrap',color:C.dim,font:'7px/1.4 ui-monospace,monospace'}}>{JSON.stringify(a.payload||{},null,2)}</pre></article>):<Empty title='No artifacts' detail='Artifacts appear only when the native runtime produces them.'/>) }
    {tab==='run'&&((selectedRun||runs.length||result)?<div><div style={{padding:9,border:'1px solid '+C.border,background:C.panel,borderRadius:7}}><b style={{color:C.teal,fontSize:8}}>RUN STATE</b><div style={{marginTop:7}}><Pill value={result?.loop_state||selectedRun?.state||'UNKNOWN'}/></div><div style={{color:C.dim,fontSize:8,marginTop:5}}>result · {result?.result_state||selectedRun?.result_state||'—'}</div></div>{runs.slice().reverse().map(r=><button key={r.run_id} onClick={()=>setSelectedRun(r)} style={{width:'100%',textAlign:'left',marginTop:5,padding:8,border:'1px solid '+(selectedRun?.run_id===r.run_id?C.strong:C.border),background:C.panel,color:C.muted,borderRadius:7,cursor:'pointer',fontSize:8}}>{short(r.run_id)} · {human(r.state)} · {human(r.result_state||'NO_RESULT')}</button>)}</div>:<Empty title='No run selected' detail='Run metadata will appear after execution.'/>) }
   </div></aside>
  </div></div>;
}