import React,{useEffect,useState} from 'react';
import {useAuth} from '../contexts/AuthContext';
import {setApiAuthToken,apiFetch} from '../lib/apiClient';

const STEPS=[
 {n:1,label:'Enterprise',title:'Create enterprise workspace context'},
 {n:2,label:'Workload',title:'Establish the pilot workload'},
 {n:3,label:'Workstreams',title:'Establish workstream records'},
 {n:4,label:'Members',title:'Assign member relationships and ownership'},
 {n:5,label:'Operating context',title:'Attach pilot budget as operating context'},
 {n:6,label:'Week 1',title:'Create weekly objectives and tasks'},
 {n:7,label:'Dashboard',title:'Project this into the master dashboard'},
];
const card={padding:18,borderRadius:16,border:'1px solid rgba(233,231,223,.09)',background:'rgba(255,255,255,.025)'};
const input={width:'100%',boxSizing:'border-box' as const,padding:'11px 12px',borderRadius:9,border:'1px solid rgba(233,231,223,.12)',background:'rgba(0,0,0,.18)',color:'#E9E7DF'};
const btn={padding:'10px 14px',borderRadius:9,border:'1px solid rgba(201,168,76,.30)',background:'rgba(201,168,76,.08)',color:'#E9E7DF',cursor:'pointer'};
const sectionKeys=['context','pilot_workload','workstreams','members','operating_context','week_one','dashboard_config'];

function pretty(v:any){return typeof v==='string'?v:JSON.stringify(v??{},null,2)}
function parse(v:string){try{return JSON.parse(v)}catch{return v}}

export default function EnterpriseConsole({onNavigate}:{onNavigate?:(v:any)=>void}){
 const {isAuthenticated,user}=useAuth(); const [list,setList]=useState<any[]>([]); const [enterprise,setEnterprise]=useState<any>(); const [step,setStep]=useState(1); const [data,setData]=useState<any>({}); const [analysis,setAnalysis]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [dashboard,setDashboard]=useState<any>();
 useEffect(()=>setApiAuthToken(user?.idToken??null),[user?.idToken]);
 const load=async()=>{try{const r=await apiFetch('/solspire/enterprise/workspaces',{headers:{}});const d=await r.json();if(!r.ok)throw new Error(d?.detail||'Unable to load enterprises');setList(d.enterprises||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load enterprises')}};
 useEffect(()=>{if(isAuthenticated)void load()},[isAuthenticated]);
 const create=async()=>{setBusy(true);setError('');try{const r=await apiFetch('/solspire/enterprise/workspaces',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw new Error(d?.detail||'Unable to create enterprise');setEnterprise(d.enterprise);setStep(1);setData({});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create enterprise')}finally{setBusy(false)}};
 const open=(e:any)=>{setEnterprise(e);setStep(Math.min(e.onboarding_step||1,7));setData(e[sectionKeys[Math.min(e.onboarding_step||1,7)-1]]||{})};
 const save=async()=>{if(!enterprise)return;setBusy(true);setError('');try{const r=await apiFetch(`/solspire/enterprise/workspaces/${enterprise.enterprise_id}/steps/${step}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data})});const d=await r.json();if(!r.ok)throw new Error(d?.detail||'Unable to save step');setEnterprise(d.enterprise);if(step<7){setStep(step+1);setData(d.enterprise[sectionKeys[step]]||{})}}catch(e){setError(e instanceof Error?e.message:'Unable to save step')}finally{setBusy(false)}};
 const ask=async()=>{if(!enterprise)return;setBusy(true);setError('');try{const message=`Act as an advisory enterprise architect. Analyze onboarding step ${step} for this enterprise. Identify missing information, structural risks, relationships, dependencies and useful questions. Do not invent facts, authorize actions, or execute work. Preserve UNKNOWN. User-provided context: ${JSON.stringify(data)}`;const r=await apiFetch('/api/commune/resonance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,history:[],session_id:`enterprise-${enterprise.enterprise_id}`})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Arkana unavailable');setAnalysis(d.reply||'No advisory response returned');await apiFetch(`/solspire/enterprise/workspaces/${enterprise.enterprise_id}/analysis`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({step:`0${step}`,context:{input:data,advisory:d.reply||''}})})}catch(e){setError(e instanceof Error?e.message:'Arkana unavailable')}finally{setBusy(false)}};
 const showDashboard=async()=>{if(!enterprise)return;const r=await apiFetch(`/solspire/enterprise/workspaces/${enterprise.enterprise_id}/dashboard`,{headers:{}});const d=await r.json();if(r.ok)setDashboard(d)};
 if(!isAuthenticated)return <div style={{...card,maxWidth:700,margin:'40px auto'}}><div style={{color:'#C9A84C',fontSize:10,letterSpacing:'.14em'}}>SOLSPIRE · ENTERPRISE</div><h2>Enterprise access</h2><p style={{color:'rgba(233,231,223,.5)'}}>Sign in to enter the organizational operating layer. Solariun remains the personal canvas.</p><button style={btn} onClick={()=>onNavigate?.('gate')}>Sign in</button></div>;
 if(dashboard)return <Dashboard d={dashboard} onBack={()=>setDashboard(undefined)}/>;
 return <main style={{display:'grid',gap:16}}>
   <header><div style={{color:'#C9A84C',fontSize:10,letterSpacing:'.15em'}}>ARKADIA / SOLSPIRE</div><h1 style={{fontWeight:400,margin:'7px 0'}}>Enterprise Console</h1><p style={{color:'rgba(233,231,223,.45)',maxWidth:760,lineHeight:1.6}}>The enterprise layer for organizational workspaces, teams, projects, workloads, knowledge and files. It is deliberately separate from the personal Solariun canvas.</p></header>
   {!enterprise?<><section style={{...card,display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><strong>Create enterprise workspace</strong><div style={{fontSize:11,color:'rgba(233,231,223,.4)',marginTop:4}}>Begin the seven-step Monday control sequence as the enterprise onboarding protocol.</div></div><button style={btn} disabled={busy} onClick={()=>void create()}>{busy?'Creating…':'Create enterprise'}</button></section>{list.map(e=><button key={e.enterprise_id} onClick={()=>open(e)} style={{...card,width:'100%',textAlign:'left',color:'#E9E7DF',cursor:'pointer'}}><strong>{e.display_name}</strong><div style={{fontSize:10,color:'#C9A84C',marginTop:6}}>Step {e.onboarding_step}/7 · {e.lifecycle}</div></button>)}</>:<section style={{display:'grid',gridTemplateColumns:'230px minmax(0,1fr)',gap:14}}>
    <aside style={{...card,height:'fit-content',display:'grid',gap:5}}>{STEPS.map(s=><button key={s.n} onClick={()=>{setStep(s.n);setData(enterprise[sectionKeys[s.n-1]]||{})}} style={{padding:'11px 10px',textAlign:'left',borderRadius:9,border:`1px solid ${step===s.n?'rgba(201,168,76,.3)':'transparent'}`,background:step===s.n?'rgba(201,168,76,.07)':'transparent',color:step===s.n?'#E9E7DF':'rgba(233,231,223,.42)',cursor:'pointer'}}><span style={{color:'#C9A84C'}}>0{s.n}</span> <strong>{s.label}</strong><small style={{display:'block',marginTop:3}}>{s.title}</small></button>)}</aside>
    <section style={{display:'grid',gap:12}}><header style={card}><div style={{color:'#C9A84C',fontSize:10,letterSpacing:'.12em'}}>ENTERPRISE ONBOARDING · {enterprise.display_name}</div><h2 style={{margin:'7px 0'}}>{STEPS[step-1].title}</h2><p style={{margin:0,fontSize:11,color:'rgba(233,231,223,.42)'}}>Human-provided facts remain authoritative. Arkana analysis is advisory.</p></header>
      <StepEditor step={step} data={data} setData={setData}/>
      <div style={{...card,display:'flex',gap:8,flexWrap:'wrap'}}><button style={btn} disabled={busy} onClick={()=>void ask()}>{busy?'Analyzing…':'Ask Arkana to analyze'}</button><button style={{...btn,marginLeft:'auto'}} disabled={busy} onClick={()=>void save()}>{step<7?'Save & continue':'Save step 7'}</button>{step===7&&<button style={btn} onClick={()=>void showDashboard()}>Open master dashboard</button>}</div>
      {analysis&&<section style={{...card,borderColor:'rgba(0,212,170,.18)'}}><div style={{fontSize:10,letterSpacing:'.12em',color:'#00D4AA'}}>ARKANA · ADVISORY</div><pre style={{whiteSpace:'pre-wrap',font:'12px/1.6 Inter,system-ui,sans-serif',color:'rgba(233,231,223,.65)'}}>{analysis}</pre></section>}
    </section>
   </section>}
   {error&&<div role="alert" style={{color:'#f0a8a8'}}>{error}</div>}
 </main>
}

function StepEditor({step,data,setData}:{step:number;data:any;setData:(v:any)=>void}){if(step===1)return <section style={{...card,display:'grid',gap:10}}>{[['display_name','Enterprise display name'],['legal_name','Legal name'],['industry','Industry / domain'],['jurisdiction','Jurisdiction / operating geography'],['registration_ref','Registration / identification reference'],['website','Website / public reference'],['description','Description and operating model'],['document_refs','Important documents / source references']].map(([k,l])=><label key={k} style={{display:'grid',gap:5,fontSize:10,color:'rgba(233,231,223,.5)'}}>{l}<textarea rows={k==='description'||k==='document_refs'?4:2} value={data[k]||''} onChange={e=>setData({...data,[k]:e.target.value})} style={input}/></label>)}</section>;const keys=[step===2?['name','objective','scope','success_criteria']:step===3?['workstreams','structure_notes']:step===4?['members','ownership_rules']:step===5?['currency','budget_total','allocations','operating_cadence','financial_assumptions','constraints']:step===6?['objectives','tasks','daily_rhythm','readiness_criteria']:['views','kpis','critical_path_fields','evidence_fields','refresh_policy']][0];return <section style={{...card,display:'grid',gap:10}}>{keys.map(k=><label key={k} style={{display:'grid',gap:5,fontSize:10,color:'rgba(233,231,223,.5)'}}>{k.replaceAll('_',' ')}<textarea rows={k==='tasks'||k==='workstreams'||k==='members'||k==='allocations'?7:4} value={typeof data[k]==='string'?data[k]:JSON.stringify(data[k]??'',null,2)} onChange={e=>{let v:any=e.target.value;try{v=JSON.parse(v)}catch{}setData({...data,[k]:v})}} style={input}/></label>)}</section>}

function Dashboard({d,onBack}:{d:any;onBack:()=>void}){return <main style={{display:'grid',gap:14}}><header style={card}><div style={{color:'#C9A84C',fontSize:10,letterSpacing:'.14em'}}>SOLSPIRE · MASTER DASHBOARD</div><h1 style={{fontWeight:400,margin:'7px 0'}}>{d.enterprise.name}</h1><p style={{color:'rgba(233,231,223,.45)'}}>Projection of enterprise operating context, workload, workstreams, members and Week 1 objectives.</p></header><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}>{[['Lifecycle',d.enterprise.lifecycle],['Step',`${d.enterprise.onboarding_step}/7`],['Budget',d.financial.budget_total],['Workstreams',d.control.workstreams?.length||0],['Members',d.control.members?.length||0]].map(([l,v])=><article key={l} style={card}><div style={{fontSize:9,textTransform:'uppercase',color:'rgba(233,231,223,.4)'}}>{l}</div><div style={{fontSize:22,marginTop:7}}>{v??'UNKNOWN'}</div></article>)}</section><section style={card}><strong>Operating structure</strong><pre style={{whiteSpace:'pre-wrap',font:'11px/1.55 monospace',color:'rgba(233,231,223,.52)'}}>{JSON.stringify(d.control,null,2)}</pre></section><section style={{...card,borderColor:'rgba(0,212,170,.18)'}}><strong style={{color:'#00D4AA'}}>Truthfulness boundary</strong><p style={{fontSize:11,lineHeight:1.6,color:'rgba(233,231,223,.5)'}}>{d.truthfulness.rule}</p><p style={{fontSize:11,color:'rgba(233,231,223,.4)'}}>{d.truthfulness.unknown_policy}</p></section><button style={btn} onClick={onBack}>← Return to onboarding</button></main>}
