import { apiFetch } from '../lib/apiClient';
import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { useAuth } from '../contexts/AuthContext';
import LoginPage from './LoginPage';

interface NodeEntryProps { onEnterNovaNet: () => void; onGoToOfferings?: () => void; onBack?: () => void; onAICComplete?: (seed: any) => void; }
type AnswerMap = Record<string, string | number>;
type Node = 'source'|'spark'|'breath'|'flame'|'ground'|'life'|'harmony'|'seek'|'octave'|'return_node'|'witness'|'weaver';
const NODES: Node[] = ['source','spark','breath','flame','ground','life','harmony','seek','octave','return_node','witness','weaver'];
const LABEL: Record<Node,string> = {source:'Roots',spark:'Start',breath:'People',flame:'Make',ground:'Steady',life:'Change',harmony:'Balance',seek:'Learn',octave:'See again',return_node:'Finish',witness:'Notice',weaver:'Connect'};
const QUESTIONS = [
  ['01 · FIRST FEELING','Something new shows up. What do you want to do first?',[['Find out where it came from.',{source:3,seek:1}],['Try it.',{spark:3,life:1}],['See what it could become.',{flame:2,octave:1}],['Ask a question about it.',{seek:3,witness:1}]]],
  ['02 · AN IDEA','You get a big idea. What happens first?',[['Look at it until it makes sense.',{seek:2,witness:2}],['Tell someone about it.',{breath:2,weaver:2}],['Start making it.',{spark:2,flame:2}],['Join it to other ideas.',{weaver:2,flame:2}]]],
  ['03 · A HARD THING','Something does not make sense. What do you want most?',[['Know what is under it.',{seek:3,source:1}],['See what could be possible.',{spark:2,life:2}],['Make it clear and ordered.',{ground:3,harmony:1}],['See how the parts fit.',{weaver:3,breath:1}]]],
  ['04 · SOMETHING FEELS WRONG','You enter a room and something feels wrong. What do you notice?',[['A pattern.',{witness:3,seek:1}],['How people feel with each other.',{breath:3,harmony:1}],['What is not working.',{ground:2,return_node:1}],['Something nobody has said.',{source:1,witness:2,weaver:1}]]],
  ['05 · WHEN A PLAN BREAKS','A plan stops working. What do you do first?',[['See what changed.',{witness:2,octave:2}],['Try another way.',{life:3,spark:1}],['Put things back in order.',{ground:3,harmony:1}],['Go with what happens next.',{life:2,breath:1,spark:1}]]],
  ['06 · WHEN YOU CARE','You really care about an idea. What do you do?',[['Keep looking.',{seek:3,source:1}],['Give it a shape.',{flame:2,ground:2}],['Get it moving.',{spark:3,life:1}],['Find the people and things it needs.',{weaver:3,harmony:1}]]],
  ['07 · TALKING','A talk gets hard. What comes naturally?',[['Be quiet and watch.',{witness:3,breath:1}],['Hold more than one side.',{breath:3,harmony:1}],['Look for the real thing underneath.',{seek:2,source:2}],['Help people find the same thread.',{weaver:3,harmony:1}]]],
  ['08 · A NEW TURN','Life takes you somewhere you did not expect. What do you say inside?',[['What does this mean?',{octave:2,witness:2}],['What can we do with it?',{life:2,spark:2}],['Let us find something solid first.',{ground:3,source:1}],['Maybe this is where I need to go.',{breath:1,life:2,seek:1}]]],
  ['09 · FREE TIME','You have time and a problem on your mind. What do you do?',[['Look it up.',{seek:3,source:1}],['Draw or build something.',{flame:3,spark:1}],['Put the problem in order.',{ground:3,witness:1}],['Talk about it and see what comes out.',{breath:2,weaver:2}]]],
  ['10 · LOOKING BACK','You think about something from long ago. What pulls you?',[['What I see now that I could not see then.',{octave:3,witness:1}],['Where it started.',{source:3,return_node:1}],['What it became.',{flame:2,life:2}],['The links I missed before.',{weaver:3,octave:1}]]],
  ['11 · A GOOD MOMENT','Which moment feels best?',[['Something becomes clear.',{witness:2,seek:2}],['Something begins.',{spark:3,life:1}],['Pieces fit together.',{flame:2,weaver:2}],['I can see where it is going.',{octave:2,return_node:2}]]],
  ['12 · RIGHT NOW','What feels most like you today?',[['I want to understand.',{seek:2,witness:1,source:1}],['I am becoming.',{life:2,octave:1,spark:1}],['I want to make.',{flame:2,spark:2}],['I want to connect.',{weaver:3,harmony:1}]]],
] as const;
const DEEP = [
  ['d1','I notice things before I know why.', 'witness'],
  ['d2','I can tell when it is time to begin.', 'spark'],
  ['d3','I like joining separate ideas into one.', 'flame'],
  ['d4','I keep asking when there is still more to learn.', 'seek'],
  ['d5','I can change when life changes.', 'life'],
  ['d6','I connect people, ideas, and things.', 'weaver'],
] as const;
const SCALE = ['Not me','A little','Sometimes','Often','Very me'];
const PATTERNS = [
  {name:'Pattern Maker',nodes:['seek','witness','flame'],text:'You like to notice what is there, find what it means, and make something from it.'},
  {name:'First Mover',nodes:['spark','life','flame'],text:'You like to begin, try, change, and turn ideas into action.'},
  {name:'Connector',nodes:['weaver','harmony','breath'],text:'You notice people and parts, then help them work together.'},
  {name:'Deep Seeker',nodes:['source','seek','octave'],text:'You like to go deeper, find the roots, and look again.'},
  {name:'Steady Maker',nodes:['ground','flame','harmony'],text:'You like to turn ideas into things that are clear, useful, and steady.'},
  {name:'Quiet Noticer',nodes:['witness','breath','life'],text:'You notice, feel, learn, and move when the time is right.'},
];
const AIS_URL = `${API_BASE.replace(/\/$/,'')}/api/me/ais-profile`;
function sigilFor(value:string){const chars=['◈','✦','⬡','◇','✧','◉','⌬','⟐','✺','❖','✥','△'];let n=2166136261;for(let i=0;i<value.length;i++){n^=value.charCodeAt(i);n=Math.imul(n,16777619);}return chars[(n>>>0)%chars.length];}
function score(answers:AnswerMap){const raw=Object.fromEntries(NODES.map(n=>[n,0])) as Record<Node,number>;QUESTIONS.forEach(q=>{const choice=q[2].find(o=>o[0]===answers[q[0]]);if(choice)Object.entries(choice[1]).forEach(([n,w])=>raw[n as Node]+=Number(w));});DEEP.forEach(q=>{const v=Number(answers[q[0]]||0);if(v)raw[q[2] as Node]+=v;});const ranked=[...NODES].sort((a,b)=>raw[b]-raw[a]);const pattern=PATTERNS.map(p=>({...p,score:p.nodes.reduce((s,n)=>s+raw[n],0)})).sort((a,b)=>b.score-a.score)[0];return {raw,ranked,pattern,growth:ranked[ranked.length-1]};}

export default function NodeEntry({onEnterNovaNet,onGoToOfferings,onBack,onAICComplete}:NodeEntryProps){
 const {user,isAuthenticated,profile,loading,refreshProfile}=useAuth();
 const [stage,setStage]=useState<'auth'|'test'|'result'>(isAuthenticated?'test':'auth');
 const [checking,setChecking]=useState(false);const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<AnswerMap>({});const [result,setResult]=useState<any>(null);const [saving,setSaving]=useState(false);
 useEffect(()=>{if(loading)return;if(!isAuthenticated||!user?.idToken){setStage('auth');return;}let dead=false;(async()=>{setChecking(true);try{const r=await apiFetch(AIS_PROFILE_PATH,{headers:{}});const d=r.ok?await r.json():null;const p=d?.profile?.profile;if(!dead&&d?.profile?.kind==='portfolio'&&p?.pulse){setResult(p.pulse);setStage('result');}}catch{}finally{if(!dead)setChecking(false);}})();return()=>{dead=true;};},[loading,isAuthenticated,user?.idToken]);
 const total=QUESTIONS.length+DEEP.length;const deep=index>=QUESTIONS.length;const q:any=deep?DEEP[index-QUESTIONS.length]:QUESTIONS[index];const id=q[0] as string;const current=answers[id];const displayName=profile?.display_name||user?.displayName||'Node';const sigil=useMemo(()=>sigilFor(JSON.stringify(answers)||displayName),[answers,displayName]);
 const choose=(v:string|number)=>setAnswers(a=>({...a,[id]:v}));
 const restart=()=>{setAnswers({});setIndex(0);setResult(null);setStage('test');};
 const finish=async()=>{const s=score(answers);const pulse={version:3,primary_patterns:s.ranked.slice(0,3).map(n=>({node:n,display:LABEL[n],score:s.raw[n]})),growth_edge:{node:s.growth,display:LABEL[s.growth],score:s.raw[s.growth]},pattern_cluster:s.pattern.name,pattern_text:s.pattern.text,sigil,completedAt:new Date().toISOString(),answers_count:Object.keys(answers).length};if(!user?.idToken)return;setSaving(true);try{const portfolio={version:1,identity:s.pattern.name,capabilities:s.ranked.slice(0,3).map(n=>LABEL[n]),builds:'',evidence:'',projects:'',offer:'',credentials:'',growth:[LABEL[s.growth]],mind:s.ranked.slice(0,3).map(n=>LABEL[n]).join(' · '),creating:'',values:'',becoming:LABEL[s.growth],preferredAiRole:'',seedPhrase:'',pulse};const r=await apiFetch(AIS_PROFILE_PATH,{method:'PATCH',headers:{'Content-Type':'application/json',},body:JSON.stringify({kind:'portfolio',profile:{...portfolio,completedAt:pulse.completedAt}})});if(!r.ok)throw new Error('save');await refreshProfile();setResult(pulse);onAICComplete?.(portfolio);setStage('result');}catch{}finally{setSaving(false);}};
 if(stage==='auth')return <div style={{minHeight:'100vh',background:'#0A0A0F'}}><LoginPage onSuccess={()=>setStage('test')} onBack={onBack}/></div>;
 if(checking)return <div style={{minHeight:'100vh',background:'#0A0A0F',display:'grid',placeItems:'center',color:'#00D4AA',fontFamily:'sans-serif',fontSize:11,letterSpacing:'.2em'}}>GETTING YOUR STARTING SHAPE…</div>;
 if(stage==='result'&&result)return <main style={{minHeight:'100vh',background:'#0A0A0F',padding:'48px 20px',color:'#E8E8E8'}}><div style={{maxWidth:680,margin:'0 auto',textAlign:'center'}}><p style={{fontSize:9,letterSpacing:'.3em',color:'rgba(0,212,170,.65)',marginBottom:8}}>YOUR STARTING SHAPE</p><motion.div animate={{rotate:360}} transition={{duration:24,repeat:Infinity,ease:'linear'}} style={{width:150,height:150,borderRadius:'50%',border:'1px solid rgba(201,168,76,.35)',display:'grid',placeItems:'center',margin:'0 auto 22px',fontSize:58,color:'#C9A84C',boxShadow:'0 0 70px rgba(201,168,76,.12)'}}>{result.sigil}</motion.div><h1 style={{fontFamily:'serif',fontWeight:400,fontSize:34,color:'#C9A84C',margin:'0 0 10px'}}>{result.pattern_cluster}</h1><p style={{fontFamily:'sans-serif',fontSize:15,lineHeight:1.7,color:'rgba(232,232,232,.68)',maxWidth:560,margin:'0 auto 24px'}}>{result.pattern_text}</p><p style={{fontFamily:'sans-serif',fontSize:11,color:'rgba(232,232,232,.4)',marginBottom:26}}>This is your starting shape, not a box. You can change. You can grow. You can take the reading again.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:8,marginBottom:28}}>{(result.primary_patterns||[]).map((p:any)=><div key={p.node} style={{padding:13,border:'1px solid rgba(255,255,255,.08)',borderRadius:10,background:'rgba(14,17,32,.7)'}}><div style={{fontSize:9,letterSpacing:'.18em',color:'rgba(201,168,76,.6)',textTransform:'uppercase'}}>YOU NOTICE</div><div style={{fontSize:14,marginTop:6}}>{p.display}</div></div>)}</div><div style={{display:'flex',gap:8,justifyContent:'center',flexWrap:'wrap'}}><button onClick={restart} style={{padding:'12px 18px',borderRadius:9,border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.03)',color:'#E8E8E8',cursor:'pointer'}}>↺ Take it again</button><button onClick={onEnterNovaNet} style={{padding:'12px 22px',borderRadius:9,border:'1px solid rgba(0,212,170,.5)',background:'rgba(0,212,170,.1)',color:'#00D4AA',cursor:'pointer'}}>Enter NovaNet →</button>{onGoToOfferings&&<button onClick={onGoToOfferings} style={{padding:'12px 22px',borderRadius:9,border:'1px solid rgba(201,168,76,.4)',background:'rgba(201,168,76,.07)',color:'#C9A84C',cursor:'pointer'}}>Explore offerings →</button>}</div><button onClick={()=>onBack?.()} style={{marginTop:18,background:'none',border:0,color:'rgba(232,232,232,.35)',cursor:'pointer'}}>Back</button></div></main>;
 return <main style={{minHeight:'100vh',background:'#0A0A0F',padding:'42px 20px',color:'#E8E8E8'}}><div style={{maxWidth:700,margin:'0 auto'}}><div style={{textAlign:'center',marginBottom:30}}><p style={{fontSize:9,letterSpacing:'.3em',color:'rgba(0,212,170,.65)'}}>WELCOME TO ARKADIA</p><h1 style={{fontFamily:'serif',fontWeight:400,fontSize:34,color:'#C9A84C',margin:'10px 0'}}>Let’s see what feels like you.</h1><p style={{fontFamily:'sans-serif',fontSize:13,lineHeight:1.7,color:'rgba(232,232,232,.5)',margin:0}}>There are no right answers. Pick what feels true. You can change your mind later.</p></div><div style={{display:'flex',justifyContent:'space-between',fontFamily:'sans-serif',fontSize:9,color:'rgba(232,232,232,.35)',marginBottom:10}}><span>{deep?'A little more':'Getting to know you'}</span><span>{index+1} / {total}</span></div><div style={{height:2,background:'rgba(255,255,255,.06)',marginBottom:28}}><div style={{height:2,width:`${((index+1)/total)*100}%`,background:'#00D4AA',transition:'width .2s'}}/></div><section style={{padding:'24px',background:'rgba(14,17,32,.72)',border:'1px solid rgba(0,212,170,.12)',borderRadius:14}}><p style={{fontSize:9,letterSpacing:'.22em',color:'rgba(201,168,76,.65)',textTransform:'uppercase',margin:'0 0 12px'}}>{deep?'A LITTLE MORE':q[0]}</p><h2 style={{fontFamily:'serif',fontWeight:400,fontSize:24,lineHeight:1.35,margin:'0 0 20px'}}>{q[1]}</h2><div style={{display:'grid',gap:8}}>{deep?SCALE.map((v,i)=><button key={v} onClick={()=>choose(i+1)} style={{textAlign:'left',padding:'14px 15px',borderRadius:9,border:`1px solid ${current===i+1?'rgba(0,212,170,.55)':'rgba(255,255,255,.08)'}`,background:current===i+1?'rgba(0,212,170,.08)':'rgba(255,255,255,.025)',color:current===i+1?'#00D4AA':'rgba(232,232,232,.7)',cursor:'pointer'}}>{v}</button>):q[2].map((o:any)=><button key={o[0]} onClick={()=>choose(o[0])} style={{textAlign:'left',padding:'15px',borderRadius:9,border:`1px solid ${current===o[0]?'rgba(0,212,170,.55)':'rgba(255,255,255,.08)'}`,background:current===o[0]?'rgba(0,212,170,.08)':'rgba(255,255,255,.025)',color:current===o[0]?'#00D4AA':'rgba(232,232,232,.72)',cursor:'pointer',fontSize:14,lineHeight:1.45}}>{o[0]}</button>)}</div></section><div style={{display:'flex',justifyContent:'space-between',marginTop:14}}><button onClick={()=>index?setIndex(i=>i-1):onBack?.()} style={{padding:'10px 14px',background:'none',border:0,color:'rgba(232,232,232,.35)',cursor:'pointer'}}>← Back</button><button disabled={current===undefined||saving} onClick={()=>index<total-1?setIndex(i=>i+1):finish()} style={{padding:'11px 18px',borderRadius:9,border:'1px solid rgba(0,212,170,.35)',background:current===undefined?'rgba(255,255,255,.03)':'rgba(0,212,170,.1)',color:current===undefined?'rgba(232,232,232,.25)':'#00D4AA',cursor:current===undefined?'not-allowed':'pointer'}}>{saving?'Saving…':index<total-1?'Next →':'See my shape →'}</button></div></div></main>;
}
