import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { useAuth } from '../contexts/AuthContext'
import MarkdownViewer from '../components/MarkdownViewer'
import StellarCartography from '../components/StellarCartography'
import { formatToArkadiaMarkdown } from '../lib/arkadiaFormatter'
import { API_BASE } from '../lib/apiConfig'

const C = { gold:'#C9A84C', teal:'#00D4AA', blue:'#6A9FD8', red:'#C84848', text:'rgba(232,232,232,.9)', dim:'rgba(232,232,232,.34)', card:'rgba(14,17,32,.78)', border:'rgba(0,212,170,.12)' }

type Author = { id?: string; username?: string | null; handle?: string | null; name: string; avatar?: string; avatar_url?: string | null; role?: string }
type Comment = { id:string; author:Author; content:string; timestamp:number }
type Post = { id:string; author:Author; owner_uid?:string; content:string; timestamp:number; edited_at?:number; reactions:{heart:number;fire:number;star:number;mind:number}; comments:Comment[]; reposts:number; resonance:number }

const ago = (ts:number) => { const d=Date.now()-ts; if(d<60000)return'now'; if(d<3600000)return`${Math.floor(d/60000)}m`; if(d<86400000)return`${Math.floor(d/3600000)}h`; return`${Math.floor(d/86400000)}d` }

function Avatar({author,size=42}:{author:Author;size?:number}) { return author.avatar_url ? <img src={author.avatar_url} alt="" style={{width:size,height:size,borderRadius:'50%',objectFit:'cover',border:`1px solid ${C.teal}35`}}/> : <div style={{width:size,height:size,borderRadius:'50%',display:'grid',placeItems:'center',background:'rgba(0,212,170,.08)',border:`1px solid ${C.teal}25`,color:C.teal,fontWeight:700}}>{(author.name||'N').slice(0,1).toUpperCase()}</div> }

function Composer({onCreated}:{onCreated:(p:Post)=>void}) {
  const {user,profile}=useAuth(); const [content,setContent]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const post=async()=>{const text=content.trim();if(!text||busy)return;setBusy(true);setError('');try{const r=await fetch(`${API_BASE}/api/transmissions`,{method:'POST',headers:{'Content-Type':'application/json',...(user?.idToken?{Authorization:`Bearer ${user.idToken}`}:{})},body:JSON.stringify({content:formatToArkadiaMarkdown(text),author:{name:profile?.display_name||'Node',avatar:profile?.role_sigil||'◈',role:profile?.role||'Node'}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'Could not transmit');onCreated(d.transmission);setContent('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:12,padding:14,marginBottom:14}}><div style={{display:'flex',gap:10}}><Avatar author={{name:profile?.display_name||'Node',avatar_url:profile?.avatar_url,avatar:profile?.role_sigil}} size={40}/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Share something with the field…" rows={3} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey))post()}} style={{flex:1,resize:'none',padding:10,background:'rgba(0,0,0,.22)',border:`1px solid ${C.border}`,borderRadius:9,color:C.text,outline:'none',lineHeight:1.5}}/></div><div style={{display:'flex',justifyContent:'flex-end',alignItems:'center',gap:10,marginTop:9}}>{error&&<span style={{color:'#E98C8C',fontSize:10,marginRight:'auto'}}>{error}</span>}<button onClick={post} disabled={!content.trim()||busy} style={{padding:'8px 15px',borderRadius:8,border:`1px solid ${C.teal}35`,background:`${C.teal}12`,color:C.teal,cursor:'pointer'}}>{busy?'Transmitting…':'⟐ Transmit'}</button></div></div>
}

function PostCard({post,myUid,onChanged}:{post:Post;myUid?:string;onChanged:(p:Post)=>void}) {
  const {user}=useAuth(); const own=!!myUid&&post.owner_uid===myUid; const [editing,setEditing]=useState(false); const [draft,setDraft]=useState(post.content); const [saving,setSaving]=useState(false); const [comments,setComments]=useState(false); const [comment,setComment]=useState('')
  const headers=useMemo(()=>user?.idToken?{Authorization:`Bearer ${user.idToken}`}:{},[user?.idToken])
  const save=async()=>{if(!draft.trim())return;setSaving(true);try{const r=await fetch(`${API_BASE}/api/transmissions/${post.id}`,{method:'PATCH',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({content:draft.trim()})});const d=await r.json().catch(()=>({}));if(r.ok){onChanged(d.transmission);setEditing(false)}}finally{setSaving(false)}}
  const del=async()=>{if(!confirm('Delete this transmission?'))return;const r=await fetch(`${API_BASE}/api/transmissions/${post.id}`,{method:'DELETE',headers});if(r.ok)onChanged({...post,id:'__deleted__'})}
  const react=async(type:'heart'|'fire'|'star'|'mind')=>{const r=await fetch(`${API_BASE}/api/transmissions/${post.id}/react`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({type})});if(r.ok){const d=await r.json();onChanged({...post,reactions:d.reactions})}}
  const addComment=async()=>{if(!comment.trim())return;const r=await fetch(`${API_BASE}/api/transmissions/${post.id}/comment`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({content:comment.trim(),author:{name:'Node',avatar:'◈',role:'Node'}})});if(r.ok){const d=await r.json();onChanged({...post,comments:[...(post.comments||[]),d.comment]});setComment('')}}
  return <motion.article initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:12,overflow:'hidden',marginBottom:10}}>
    <div style={{padding:'12px 14px',display:'flex',alignItems:'center',gap:10}}><Avatar author={post.author}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:13,fontWeight:700}}>{post.author.name}</div><div style={{fontSize:9,color:C.dim}}>{post.author.handle||post.author.role||'Node'} · {ago(post.timestamp)}{post.edited_at?' · edited':''}</div></div>{post.resonance!==undefined&&<span style={{fontSize:9,color:C.blue}}>◉ {post.resonance}%</span>}{own&&<div style={{display:'flex',gap:5}}><button onClick={()=>{setDraft(post.content);setEditing(v=>!v)}} style={{background:'none',border:`1px solid ${C.blue}30`,color:C.blue,borderRadius:6,padding:'4px 7px',cursor:'pointer',fontSize:10}}>{editing?'Cancel':'Edit'}</button><button onClick={del} style={{background:'none',border:`1px solid ${C.red}35`,color:C.red,borderRadius:6,padding:'4px 7px',cursor:'pointer',fontSize:10}}>Delete</button></div>}</div>
    <div style={{padding:'0 14px 13px'}}>{editing?<><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={5} style={{width:'100%',boxSizing:'border-box',padding:10,background:'rgba(0,0,0,.22)',border:`1px solid ${C.blue}30`,borderRadius:8,color:C.text,resize:'vertical',outline:'none'}}/><button onClick={save} disabled={saving} style={{marginTop:7,padding:'7px 12px',background:`${C.blue}12`,border:`1px solid ${C.blue}30`,borderRadius:7,color:C.blue,cursor:'pointer'}}>{saving?'Saving…':'Save changes'}</button></>:<MarkdownViewer content={post.content} compact/>}</div>
    <div style={{padding:'7px 14px',borderTop:'1px solid rgba(255,255,255,.04)',display:'flex',gap:9}}>{(['heart','fire','star','mind'] as const).map(t=><button key={t} onClick={()=>react(t)} style={{background:'none',border:0,color:C.dim,cursor:'pointer',fontSize:11}}>{t==='heart'?'💜':t==='fire'?'🔥':t==='star'?'✨':'🧠'} {post.reactions?.[t]||0}</button>)}<button onClick={()=>setComments(v=>!v)} style={{marginLeft:'auto',background:'none',border:0,color:C.dim,cursor:'pointer',fontSize:11}}>💬 {post.comments?.length||0}</button></div>
    {comments&&<div style={{borderTop:'1px solid rgba(255,255,255,.04)',padding:10}}>{(post.comments||[]).map(c=><div key={c.id} style={{display:'flex',gap:8,padding:'7px 4px'}}><Avatar author={c.author} size={26}/><div style={{fontSize:11}}><strong>{c.author.name}</strong> {c.content}<div style={{fontSize:8,color:C.dim,marginTop:2}}>{ago(c.timestamp)}</div></div></div>)}<div style={{display:'flex',gap:7,marginTop:5}}><input value={comment} onChange={e=>setComment(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addComment()} placeholder="Say something…" style={{flex:1,padding:'8px 11px',background:'rgba(0,0,0,.2)',border:`1px solid ${C.border}`,borderRadius:16,color:C.text,outline:'none'}}/><button onClick={addComment} style={{border:0,background:`${C.teal}12`,color:C.teal,borderRadius:16,padding:'0 12px',cursor:'pointer'}}>Post</button></div></div>}
  </motion.article>
}

export default function NovaNetSocialPage(){
  const {user,profile,isAuthenticated}=useAuth(); const [posts,setPosts]=useState<Post[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`${API_BASE}/api/transmissions?limit=60`);const d=await r.json();if(!r.ok)throw new Error(d.detail||'Feed unavailable');setPosts(d.transmissions||[])}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[])
  useEffect(()=>{load()},[load])
  const changed=(p:Post)=>setPosts(prev=>p.id==='__deleted__'?prev.filter(x=>x.id!==p.id):prev.map(x=>x.id===p.id?p:x))
  return <div style={{minHeight:'calc(100vh - 57px)',color:C.text,fontFamily:'sans-serif'}}><div style={{maxWidth:900,margin:'0 auto',padding:'16px 14px 40px'}}><StellarCartography/><header style={{padding:'18px 0 13px'}}><div style={{fontSize:9,letterSpacing:'.3em',textTransform:'uppercase',color:`${C.blue}80`}}>Arkadia · Public Field</div><h1 style={{fontFamily:'Cinzel,serif',fontSize:25,color:C.blue,margin:'5px 0'}}>NovaNet</h1><p style={{fontSize:11,color:C.dim,margin:0}}>Transmit ideas. Meet Nodes. Carry your identity with you.</p></header>{isAuthenticated?<Composer onCreated={p=>setPosts(prev=>[p,...prev])}/>:<div style={{padding:12,marginBottom:14,border:`1px solid ${C.border}`,borderRadius:10,color:C.dim,fontSize:10}}>Sign in to transmit and participate in the field.</div>}{loading?<div style={{padding:30,textAlign:'center',color:C.dim}}>Reading the field…</div>:error?<div style={{padding:30,textAlign:'center',color:'#E98C8C'}}>{error}</div>:posts.map(p=><PostCard key={p.id} post={p} myUid={user?.uid} onChanged={changed}/>)}</div></div>
}
