import React from 'react';
import {radarTargets,insertionBrief} from '../data/opportunityRadar';
export default function OpportunityRadarPage(){const w1=radarTargets.filter(t=>t.id.startsWith('W1')),w2=radarTargets.filter(t=>t.id.startsWith('W2'));return <div style={{display:'grid',gap:18}}>
<section className="solspire-object" style={{cursor:'default'}}><div className="solspire-kicker">OPPORTUNITY RADAR · SAPZ CAPTURE</div><h2 className="solspire-title">NPCO/SAPZ/25/2005</h2><p className="solspire-object-summary">Capture state persists in the Arkadia repository. Deadline: 30 Oct 2026 · 16:00 WAT. Bidder status remains unknown until directly verified.</p></section>
<section><div className="solspire-kicker" style={{color:'#00D4AA',marginBottom:8}}>WAVE 1 · CONTACT</div><div style={{display:'grid',gap:12}}>{w1.map(t=><Target key={t.id} t={t}/>)}</div></section>
<section><div className="solspire-kicker" style={{color:'#6A9FD8',marginBottom:8}}>WAVE 2 · QUEUED</div><div style={{display:'grid',gap:12}}>{w2.map(t=><Target key={t.id} t={t}/>)}</div></section>
<section className="solspire-object" style={{cursor:'default'}}><div className="solspire-kicker" style={{color:'#00D4AA'}}>1-PAGE INSERTION BRIEF</div><h3 className="solspire-title">{insertionBrief.title}</h3><p className="solspire-object-summary">{insertionBrief.problem}</p><p className="solspire-object-summary"><strong>Proposition:</strong> {insertionBrief.proposition}</p>{insertionBrief.contributions.map(x=><div key={x} style={{fontSize:12,color:'rgba(232,232,232,.58)',marginTop:6}}>• {x}</div>)}<div style={{marginTop:14,paddingTop:12,borderTop:'1px solid rgba(255,255,255,.08)'}}><div className="solspire-kicker">HONEST BOUNDARY</div>{insertionBrief.boundaries.map(x=><div key={x} style={{fontSize:11,color:'rgba(232,232,232,.45)',marginTop:5}}>• {x}</div>)}</div></section>
</div>}
function Target({t}:{t:typeof radarTargets[number]}){return <article className="solspire-object" style={{cursor:'default'}}><div className="solspire-kicker">{t.id} · {t.state}</div><h3 className="solspire-title">{t.name}</h3><p className="solspire-object-summary">{t.signal}</p><div style={{display:'grid',gap:6,fontSize:11,color:'rgba(232,232,232,.52)'}}><div><b>Doorway:</b> {t.doorway}</div>{t.contact&&<div><b>Technical:</b> {t.contact}</div>}{t.email&&<div><b>Email:</b> <a href={`mailto:${t.email}`} style={{color:'#00D4AA'}}>{t.email}</a></div>}{t.phone&&<div><b>Phone:</b> <a href={`tel:${t.phone.replace(/[^+\\d]/g,'')}`} style={{color:'#00D4AA'}}>{t.phone}</a></div>}<div><b>Fit:</b> {t.fit}</div><div><b>Lowest-friction entry:</b> {t.entry}</div><div><b>RFP participation:</b> {t.bidStatus}</div></div></article>}
