import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../contexts/AuthContext';
import { API_BASE as API_BASE_CFG } from '../lib/apiConfig';
import ScrollListenButton from '../components/ScrollListenButton';

const API_BASE = API_BASE_CFG.replace(/\/$/, '');
interface Loop { id: string; loop: string; status: string; priority: number }
interface Phase { name: string; days: string; focus: string; anchor: string }
interface Scroll { id: string; label: string; category: string; description: string; source: string; preview?: string }
interface ColNode { display_name: string; role: string; role_sigil: string; ims_id?: string; status: string; access_level: number }
interface Codex { display_name: string; ims_id: string; role: string; soul_function: string; field_frequency?: string; name_decode?: Record<string, string>; shadow_states?: string[]; soul_gifts?: string[]; open_loops?: Loop[]; access_tools?: string[]; '90_day_architecture'?: Record<string, Phase>; [k: string]: unknown }
interface NodeProfile { display_name: string; role: string; role_sigil: string; ims_id?: string; access_level: number }
interface PersonalData { node: NodeProfile; codex: Codex; collective: ColNode[]; system: { tools_count: number } }
const CAT_COLOR: Record<string, string> = { NEURAL_SPINE: '#00D4AA', CREATIVE_OS: '#C9A84C', COLLECTIVE: '#6A9FD8', GOVERNANCE: '#E85246' };
const CAT_LINK: Record<string, string> = { NEURAL_SPINE: 'Soul Function', CREATIVE_OS: 'Soul Gifts', COLLECTIVE: 'Open Loops', GOVERNANCE: '90-Day Arc' };
const CAT_ORDER = ['NEURAL_SPINE', 'CREATIVE_OS', 'COLLECTIVE', 'GOVERNANCE'];
function Label({ children, color = 'rgba(232,232,232,0.28)' }: { children: React.ReactNode; color?: string }) { return <p style={{ fontFamily: 'monospace', fontSize: '8px', letterSpacing: '0.3em', textTransform: 'uppercase', color, margin: '0 0 9px' }}>{children}</p>; }
function SectionBox({ children, accent = 'rgba(255,255,255,0.055)', style }: { children: React.ReactNode; accent?: string; style?: React.CSSProperties }) { return <div style={{ border: `1px solid ${accent}`, borderRadius: '13px', overflow: 'hidden', marginBottom: '22px', ...style }}>{children}</div>; }
function SectionHead({ label, color = '#00D4AA', right }: { label: string; color?: string; right?: React.ReactNode }) { return <div style={{ padding: '10px 18px', background: `${color}0A`, borderBottom: `1px solid ${color}18`, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span style={{ fontFamily: 'monospace', fontSize: '9px', letterSpacing: '0.28em', textTransform: 'uppercase', color: `${color}95` }}>{label}</span>{right}</div>; }
export default function PersonalCodex({ onNavigate }: { onNavigate?: (v: 'login') => void } = {}) {
  const { isAuthenticated, user, profile, codex: authCodex } = useAuth();
  const [data, setData] = useState<PersonalData | null>(null); const [scrolls, setScrolls] = useState<Scroll[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [activeCat, setActiveCat] = useState<string | null>(null);
  const resolvedName = (profile?.display_name && profile.display_name.trim()) || user?.displayName || (user?.email ? user.email.split('@')[0] : '') || 'Signed-in user';
  const resolvedRole = profile?.role || 'Authenticated Node';
  const resolvedSigil = profile?.role_sigil || '◈';
  const hasImsCodex = Boolean(profile?.node_key && authCodex);
  useEffect(() => {
    if (!isAuthenticated) { setLoading(false); setData(null); return; }
    const nodeFromAuth: NodeProfile = { display_name: resolvedName, role: resolvedRole, role_sigil: resolvedSigil, ims_id: profile?.ims_id || undefined, access_level: profile?.access_level ?? 0 };
    if (hasImsCodex && authCodex) setData({ node: nodeFromAuth, codex: authCodex as unknown as Codex, collective: [], system: { tools_count: 0 } });
    else setData({ node: nodeFromAuth, codex: { display_name: resolvedName, ims_id: profile?.ims_id || '—', role: resolvedRole, soul_function: 'Your private Knowledge OS and Oracle memory are scoped to this account.' }, collective: [], system: { tools_count: 0 } });
    setLoading(false);
    fetch(`${API_BASE}/api/codex`).then(r => r.ok ? r.json() : null).then(corpus => { if (!corpus) return; const raw = corpus.scrolls || {}; setScrolls(typeof raw === 'object' && !Array.isArray(raw) ? Object.values(raw) as Scroll[] : raw as Scroll[]); }).catch(() => {});
  }, [isAuthenticated, user?.uid, user?.email, user?.displayName, profile?.display_name, profile?.role, profile?.node_key, profile?.access_level, profile?.ims_id, profile?.role_sigil, hasImsCodex, authCodex, resolvedName, resolvedRole, resolvedSigil]);
  if (!isAuthenticated) return <div style={{ minHeight: '60vh', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 }}><div style={{ maxWidth: 420, textAlign: 'center' }}><div style={{ fontSize: 30, color: '#C9A84C', marginBottom: 14 }}>✦</div><h2 style={{ fontFamily: 'serif', fontSize: 20, color: '#E8E8E8', margin: '0 0 8px', fontWeight: 400 }}>The Personal Codex is private</h2><p style={{ fontFamily: 'sans-serif', fontSize: 12, color: 'rgba(232,232,232,0.48)', lineHeight: 1.6, margin: '0 0 22px' }}>Your nine-layer crystalline identity stack is only available to authenticated nodes. Sign in to retrieve it.</p>{onNavigate && <button onClick={() => onNavigate('login')} style={{ padding: '11px 28px', background: 'rgba(201,168,76,0.1)', border: '1px solid rgba(201,168,76,0.3)', borderRadius: 10, color: 'rgba(201,168,76,0.9)', fontFamily: 'sans-serif', fontSize: 11, letterSpacing: '0.12em', textTransform: 'uppercase', cursor: 'pointer' }}>Sign in</button>}</div></div>;
  if (loading) return <div style={{ padding: '90px 20px', textAlign: 'center' }}><motion.div animate={{ opacity: [0.2, 0.8, 0.2] }} transition={{ repeat: Infinity, duration: 2.2 }}><p style={{ fontFamily: 'monospace', fontSize: '9px', letterSpacing: '0.35em', textTransform: 'uppercase', color: '#00D4AA' }}>EchoField Recursion Initialising…</p></motion.div></div>;
  if (error || !data) return <div style={{ padding: '60px 20px', textAlign: 'center', maxWidth: '480px', margin: '0 auto' }}><p style={{ fontSize: 24 }}>⟐</p><h2 style={{ fontFamily: 'serif', fontSize: 20, color: '#C9A84C' }}>Neural Spine Offline</h2><p style={{ fontFamily: 'sans-serif', fontSize: 11, color: 'rgba(232,232,232,0.35)', lineHeight: 1.8 }}>{error || 'Could not reach the Oracle Temple. Ensure the backend is running.'}</p></div>;
  const { node, codex } = data; const freq = codex.field_frequency || '117 Hz'; const tools = codex.access_tools || []; const loops = (codex.open_loops || []).sort((a,b) => (a.priority ?? 9) - (b.priority ?? 9)); const arch = codex['90_day_architecture'] as Record<string, Phase> | undefined;
  const scrollsByCategory: Record<string, Scroll[]> = {}; for (const s of scrolls) { const c = s.category || 'OTHER'; (scrollsByCategory[c] ||= []).push(s); } const cats = CAT_ORDER.filter(c => scrollsByCategory[c]);
  return <div style={{ maxWidth: 760, margin: '0 auto', paddingBottom: 90 }}>
    <motion.div initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} style={{marginBottom:24,padding:'20px 24px',background:'rgba(201,168,76,.04)',border:'1px solid rgba(201,168,76,.16)',borderRadius:14}}><Label color="rgba(201,168,76,.6)">Authenticated workspace identity</Label><div style={{display:'flex',alignItems:'center',gap:14}}><div style={{width:46,height:46,borderRadius:14,display:'grid',placeItems:'center',background:'rgba(201,168,76,.08)',border:'1px solid rgba(201,168,76,.2)',fontSize:20,color:'#C9A84C'}}>{resolvedSigil}</div><div><h1 style={{fontFamily:'Georgia,serif',fontWeight:400,fontSize:24,color:'#E9E7DF',margin:0}}>{node.display_name}</h1><div style={{marginTop:4,fontFamily:'monospace',fontSize:9,letterSpacing:'.12em',textTransform:'uppercase',color:'rgba(233,231,223,.38)'}}>{node.role} · authenticated</div></div><div style={{marginLeft:'auto',textAlign:'right'}}><div style={{fontFamily:'monospace',fontSize:9,color:'#00D4AA'}}>ONLINE</div><div style={{fontFamily:'monospace',fontSize:8,color:'rgba(233,231,223,.25)',marginTop:3}}>{freq}</div></div></div></motion.div>
    <SectionBox accent="rgba(0,212,170,.12)"><SectionHead label="Identity spine" color="#00D4AA" /><div style={{padding:20}}><Label color="rgba(0,212,170,.55)">Soul function</Label><p style={{fontFamily:'Georgia,serif',fontSize:18,lineHeight:1.65,color:'rgba(233,231,223,.72)',margin:0}}>{codex.soul_function}</p></div></SectionBox>
    {codex.name_decode && <SectionBox accent="rgba(201,168,76,.11)"><SectionHead label="Name decoding" color="#C9A84C" /><div style={{padding:18,display:'grid',gap:10}}>{Object.entries(codex.name_decode).map(([k,v])=><div key={k} style={{display:'flex',gap:16,padding:'10px 0',borderBottom:'1px solid rgba(255,255,255,.04)'}}><span style={{width:120,fontFamily:'monospace',fontSize:8,color:'rgba(233,231,223,.28)',textTransform:'uppercase'}}>{k}</span><span style={{fontFamily:'Inter,system-ui,sans-serif',fontSize:11,color:'rgba(233,231,223,.62)'}}>{v}</span></div>)}</div></SectionBox>}
    {tools.length > 0 && <SectionBox><SectionHead label="Access tools" color="#6A9FD8" /><div style={{padding:18,display:'flex',flexWrap:'wrap',gap:7}}>{tools.map(t=><span key={t} style={{fontFamily:'monospace',fontSize:8,padding:'6px 8px',borderRadius:6,background:'rgba(106,159,216,.08)',border:'1px solid rgba(106,159,216,.14)',color:'rgba(106,159,216,.7)'}}>{t}</span>)}</div></SectionBox>}
    {loops.length > 0 && <SectionBox><SectionHead label="Open loops" color="#C9A84C" /><div style={{padding:'4px 18px'}}>{loops.map(l=><div key={l.id} style={{padding:'12px 0',borderBottom:'1px solid rgba(255,255,255,.04)',display:'flex',gap:12}}><span style={{fontFamily:'monospace',fontSize:9,color:'#C9A84C'}}>L{l.priority}</span><div><div style={{fontFamily:'Inter,system-ui,sans-serif',fontSize:11,color:'rgba(233,231,223,.65)'}}>{l.loop}</div><div style={{marginTop:3,fontFamily:'monospace',fontSize:8,color:'rgba(233,231,223,.24)'}}>{l.status}</div></div></div>)}</div></SectionBox>}
    {arch && <SectionBox><SectionHead label="90-day architecture" color="#B08DE8" /><div style={{padding:18,display:'grid',gap:10}}>{Object.entries(arch).map(([k,p])=><div key={k} style={{padding:'11px 0',borderBottom:'1px solid rgba(255,255,255,.04)'}}><div style={{fontFamily:'monospace',fontSize:8,color:'#B08DE8'}}>{k} · {p.days}</div><div style={{marginTop:5,fontFamily:'Georgia,serif',fontSize:13,color:'rgba(233,231,223,.62)'}}>{p.name || p.focus}</div></div>)}</div></SectionBox>}
    {cats.map(c=><SectionBox key={c} accent={`${CAT_COLOR[c]}18`}><SectionHead label={CAT_LINK[c]} color={CAT_COLOR[c]} right={<button onClick={()=>setActiveCat(activeCat===c?null:c)} style={{border:0,background:'transparent',color:`${CAT_COLOR[c]}80`,cursor:'pointer',fontFamily:'monospace',fontSize:8}}>{activeCat===c?'COLLAPSE':'EXPLORE'}</button>} />{activeCat===c && <div style={{padding:14,display:'grid',gap:8}}>{scrollsByCategory[c].map(s=><article key={s.id} style={{padding:12,border:'1px solid rgba(255,255,255,.05)',borderRadius:9}}><div style={{fontFamily:'Georgia,serif',fontSize:13,color:'#E9E7DF'}}>{s.label}</div><div style={{marginTop:5,fontFamily:'Inter,system-ui,sans-serif',fontSize:10,lineHeight:1.5,color:'rgba(233,231,223,.35)'}}>{s.description}</div></article>)}</div>}</SectionBox>)}
  </div>;
}
