import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { useAuth } from '../contexts/AuthContext'
import MarkdownViewer from '../components/MarkdownViewer'
import { formatToArkadiaMarkdown } from '../lib/arkadiaFormatter'

const API_BASE = (import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/$/, '')
const C = { teal:'#00D4AA', blue:'#6A9FD8', gold:'#C9A84C', red:'#C84848', text:'rgba(232,232,232,.9)', muted:'rgba(232,232,232,.56)', dim:'rgba(232,232,232,.32)', card:'rgba(14,17,32,.78)', border:'rgba(106,159,216,.14)' }

type Tab = 'field' | 'nodes' | 'reasomate'
type NodeProfile = { uid:string; username?:string|null; handle?:string|null; display_name:string; bio?:string|null; avatar_url?:string|null }
type Author = { id?:string; name:string; avatar?:string; role?:string; avatar_url?:string|null; username?:string|null; handle?:string|null }
type Comment = { id:string; author:Author; content:string; timestamp:number }
type Post = { id:string; owner_uid?:string|null; author:Author; content:string; timestamp:number; edited_at?:number; reactions:Record<string,number>; comments:Comment[]; reposts:number; resonance:number }
type Message = { id:string; sender_uid:string; recipient_uid:string; content:string; timestamp:number }
type Relation = { interaction_count:number; first_interaction_at?:number|null; last_interaction_at?:number|null; shared_memory_source:string; memory_policy:string }

const ago=(ts?:number)=>{if(!ts)return'';const d=Date.now()-ts;if(d<60000)return'now';if(d<3600000)return`${Math.floor(d/60000)}m`;if(d<86400000)return`${Math.floor(d/3600000)}h`;return`${Math.floor(d/86400000)}d`}
const btn=(color:string,disabled=false):React.CSSProperties=>({padding:'7px 11px',background:`${color}10`,border:`1px solid ${color}35`,borderRadius:8,color:disabled?C.dim:color,cursor:disabled?'not-allowed':'pointer',fontSize:9,letterSpacing:'.1em',textTransform:'uppercase'})

function Avatar({node,size=40}:{node:Partial<NodeProfile>&{name?:string;avatar?:string;avatar_url?:string|null};size?:number}){return node.avatar_url?<img src={node.avatar_url} alt="" style={{width:size,height:size,borderRadius:'50%',objectFit:'cover',border:`1px solid ${C.blue}35`}}/>:<div style={{width:size,height:size,borderRadius:'50%',display:'grid',placeItems:'center',background:'rgba(106,159,216,.1)',border:`1px solid ${C.blue}30`,color:C.blue,fontWeight:700}}>{node.avatar||(node.name||node.display_name||'N').slice(0,1).toUpperCase()}</div>}

function Composer({token,profile,onCreated}:{token:string;profile:any;onCreated:(p:Post)=>void}){const[text,setText]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{if(!text.trim()||busy)return;setBusy(true);try{const r=await fetch(`${API_BASE}/api/transmissions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content:formatToArkadiaMarkdown(text),author:{name:profile?.display_name||'Node',avatar:profile?.role_sigil||'◈',role:profile?.role||'Node'}})});const d=await r.json().catch(()=>({}));if(r.ok){onCreated(d.transmission);setText('')}}finally{setBusy(false)}};return <div style={{padding:14,background:C.card,border:`1px solid ${C.border}`,borderRadius:12,marginBottom:12}}><div style={{display:'flex',gap:10}}><Avatar node={{name:profile?.display_name,avatar:profile?.role_sigil,avatar_url:profile?.avatar_url}}/><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&submit()} placeholder="Say something to the field…" rows={3} style={{flex:1,resize:'none',padding:10,background:'rgba(0,0,0,.22)',border:'1px solid rgba(255,255,255,.07)',borderRadius:9,color:C.text,outline:'none'}}/></div><div style={{display:'flex',justifyContent:'flex-end',marginTop:8}}><button onClick={submit} disabled={!text.trim()||busy} style={btn(C.teal,!text.trim()||busy)}>{busy?'Transmitting…':'Transmit'}</button></div></div>}

function PostCard({post,token,myUid,onChange}:{post:Post;token:string;myUid:string;onChange:(p:Post|null)=>void}){const[editing,setEditing]=useState(false);const[draft,setDraft]=useState(post.content);const[busy,setBusy]=useState(false);const own=post.owner_uid===myUid;const save=async()=>{if(!draft.trim())return;setBusy(true);try{const r=await fetch(`${API_BASE}/api/transmissions/${post.id}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content:draft.trim()})});if(r.ok){const d=await r.json();onChange(d.transmission);setEditing(false)}}finally{setBusy(false)}};const remove=async()=>{if(!confirm('Delete this transmission?'))return;setBusy(true);try{const r=await fetch(`${API_BASE}/api/transmissions/${post.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});if(r.ok)onChange(null)}finally{setBusy(false)}};return <motion.article initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:12,overflow:'hidden'}}><div style={{padding:12,display:'flex',gap:9,alignItems:'center'}}><Avatar node={post.author}/><div style={{flex:1}}><div style={{fontSize:12,fontWeight:600}}>{post.author.name||'Node'}</div><div style={{fontSize:9,color:C.dim}}>{post.author.handle||post.author.username||post.author.role||'Node'} · {ago(post.timestamp)}{post.edited_at?' · edited':''}</div></div>{own&&<div style={{display:'flex',gap:5}}><button onClick={()=>{setDraft(post.content);setEditing(v=>!v)}} style={btn(C.blue)}>{editing?'Cancel':'Edit'}</button><button onClick={remove} disabled={busy} style={btn(C.red,busy)}>Delete</button></div>}</div><div style={{padding:'0 13px 13px'}}>{editing?<><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={5} style={{width:'100%',boxSizing:'border-box',background:'rgba(0,0,0,.2)',border:`1px solid ${C.blue}30`,borderRadius:9,color:C.text,padding:10,resize:'vertical',outline:'none'}}/><div style={{display:'flex',justifyContent:'flex-end',marginTop:6}}><button onClick={save} disabled={busy||!draft.trim()} style={btn(C.teal,busy||!draft.trim())}>{busy?'Saving…':'Save changes'}</button></div></>:<MarkdownViewer content={post.content} compact/>}</div></motion.article>}

function NodesTab({token,onOpen}:{token:string;onOpen:(n:NodeProfile)=>void}){const[q,setQ]=useState('');const[nodes,setNodes]=useState<NodeProfile[]>([]);const[loading,setLoading]=useState(false);useEffect(()=>{let alive=true;setLoading(true);const t=setTimeout(async()=>{try{const r=await fetch(`${API_BASE}/api/social/nodes?q=${encodeURIComponent(q)}&limit=50`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(alive)setNodes(d.nodes||[])}finally{if(alive)setLoading(false)}},180);return()=>{alive=false;clearTimeout(t)}},[q,token]);return <div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a Node by name, @handle or bio…" style={{width:'100%',boxSizing:'border-box',padding:10,marginBottom:12,background:'rgba(255,255,255,.03)',border:`1px solid ${C.border}`,borderRadius:10,color:C.text,outline:'none'}}/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10}}>{nodes.map(n=><button key={n.uid} onClick={()=>onOpen(n)} style={{textAlign:'left',padding:13,background:C.card,border:`1px solid ${C.border}`,borderRadius:12,color:C.text,cursor:'pointer'}}><div style={{display:'flex',gap:10,alignItems:'center'}}><Avatar node={n}/><div><div style={{fontSize:12,fontWeight:600}}>{n.display_name}</div><div style={{fontSize:9,color:C.teal}}>{n.handle||'@node'}</div></div></div>{n.bio&&<div style={{fontSize:10,color:C.dim,marginTop:9,lineHeight:1.5}}>{n.bio}</div>}</button>)}</div>{!loading&&!nodes.length&&<div style={{padding:25,textAlign:'center',color:C.dim,fontSize:10}}>No Nodes found.</div>}</div>}

function Thread({peer,token,myUid,onBack}:{peer:NodeProfile;token:string;myUid:string;onBack:()=>void}){const[messages,setMessages]=useState<Message[]>([]);const[relation,setRelation]=useState<Relation|null>(null);const[text,setText]=useState('');const[sending,setSending]=useState(false);const load=useCallback(async()=>{const[m,r]=await Promise.all([fetch(`${API_BASE}/api/messages/thread/${peer.uid}`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API_BASE}/api/relationships/${peer.uid}/context`,{headers:{Authorization:`Bearer ${token}`}})]);if(m.ok)setMessages((await m.json()).messages||[]);if(r.ok)setRelation((await r.json()).relationship||null)},[peer.uid,token]);useEffect(()=>{load()},[load]);const send=async()=>{if(!text.trim()||sending)return;setSending(true);try{const r=await fetch(`${API_BASE}/api/messages`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({recipient_uid:peer.uid,content:text.trim()})});if(r.ok){const d=await r.json();setMessages(v=>[...v,d.message]);setRelation(v=>v?{...v,interaction_count:v.interaction_count+1,last_interaction_at:d.message.timestamp}:v);setText('')}}finally{setSending(false)}};return <div style={{display:'flex',flexDirection:'column',minHeight:460}}><div style={{display:'flex',alignItems:'center',gap:9,paddingBottom:10,borderBottom:`1px solid ${C.border}`}}><button onClick={onBack} style={{background:'none',border:0,color:C.teal,cursor:'pointer',fontSize:16}}>←</button><Avatar node={peer} size={36}/><div style={{flex:1}}><div style={{fontSize:12}}>{peer.display_name}</div><div style={{fontSize:9,color:C.teal}}>{peer.handle}</div></div><span style={{fontSize:8,color:C.teal}}>● shared field</span></div><div style={{padding:'8px 0',fontSize:9,color:C.dim}}>{relation?.interaction_count||0} shared messages · relational context is derived from this thread</div><div style={{flex:1,overflowY:'auto',padding:'5px 0 12px'}}>{messages.map(m=><div key={m.id} style={{display:'flex',justifyContent:m.sender_uid===myUid?'flex-end':'flex-start',marginBottom:7}}><div style={{maxWidth:'78%',padding:'8px 11px',background:m.sender_uid===myUid?'rgba(0,212,170,.12)':'rgba(106,159,216,.08)',border:`1px solid ${m.sender_uid===myUid?C.teal:C.blue}20`,borderRadius:12}}><div style={{fontSize:11,lineHeight:1.5,whiteSpace:'pre-wrap'}}>{m.content}</div><div style={{fontSize:8,color:C.dim,marginTop:3}}>{ago(m.timestamp)}</div></div></div>)}</div><div style={{display:'flex',gap:6,borderTop:`1px solid ${C.border}`,paddingTop:9}}><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={`Message ${peer.display_name}…`} style={{flex:1,padding:'9px 12px',background:'rgba(0,0,0,.22)',border:`1px solid ${C.border}`,borderRadius:18,color:C.text,outline:'none'}}/><button onClick={send} disabled={sending||!text.trim()} style={btn(C.teal,sending||!text.trim())}>{sending?'…':'Send'}</button></div></div>}

function ReasoMateTab({token,myUid,onFind}:{token:string;myUid:string;onFind:()=>void}){const[convs,setConvs]=useState<any[]>([]);const[nodes,setNodes]=useState<NodeProfile[]>([]);const[peer,setPeer]=useState<NodeProfile|null>(null);useEffect(()=>{Promise.all([fetch(`${API_BASE}/api/messages/inbox`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()),fetch(`${API_BASE}/api/social/nodes`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json())]).then(([c,n])=>{setConvs(c.conversations||[]);setNodes(n.nodes||[])}).catch(()=>{})},[token]);if(peer)return <Thread peer={peer} token={token} myUid={myUid} onBack={()=>setPeer(null)}/>;return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><div><div style={{fontSize:14}}>ReasoMate</div><div style={{fontSize:9,color:C.dim}}>Private threads with shared relational context.</div></div><button onClick={onFind} style={btn(C.blue)}>Find a Node</button></div>{convs.map(c=>{const n=nodes.find(x=>x.uid===c.peer_uid);return n?<button key={c.peer_uid} onClick={()=>setPeer(n)} style={{width:'100%',display:'flex',gap:9,alignItems:'center',padding:10,marginBottom:6,textAlign:'left',background:C.card,border:`1px solid ${C.border}`,borderRadius:10,color:C.text,cursor:'pointer'}}><Avatar node={n} size={34}/><div style={{flex:1}}><div style={{fontSize:11}}>{n.display_name}</div><div style={{fontSize:9,color:C.dim}}>{c.last_message?.content?.slice(0,80)}</div></div><span style={{fontSize:8,color:C.dim}}>{ago(c.last_message?.timestamp)}</span></button>:null})}{!convs.length&&<div style={{textAlign:'center',padding:30,color:C.dim,fontSize:10}}>Your ReasoMate field is quiet. Find a Node and begin a thread.</div>}</div>}

export default function SocialFieldPage(){const{isAuthenticated,profile,user}=useAuth();const token=user?.idToken||'';const[tab,setTab]=useState<Tab>('field');const[posts,setPosts]=useState<Post[]>([]);const[nodes,setNodes]=useState<NodeProfile[]>([]);const[selected,setSelected]=useState<NodeProfile|null>(null);const load=async()=>{const[p,n]=await Promise.all([fetch(`${API_BASE}/api/transmissions?limit=60`),token?fetch(`${API_BASE}/api/social/nodes`,{headers:{Authorization:`Bearer ${token}`}}):Promise.resolve(null)]);if(p.ok)setPosts((await p.json()).transmissions||[]);if(n?.ok)setNodes((await n.json()).nodes||[])};useEffect(()=>{load()},[token]);const byUid=useMemo(()=>Object.fromEntries(nodes.map(n=>[n.uid,n])),[nodes]);if(!isAuthenticated)return <div style={{padding:40,textAlign:'center',color:C.muted}}>Sign in to enter the Social Identity + ReasoMate Field.</div>;return <div style={{minHeight:'calc(100vh - 80px)',color:C.text}}><header style={{display:'flex',alignItems:'center',gap:10,marginBottom:14}}><Avatar node={{name:profile?.display_name,avatar_url:profile?.avatar_url,avatar:profile?.role_sigil}} size={38}/><div><h2 style={{margin:0,fontFamily:'Cinzel,serif',fontSize:19}}>The Social Field</h2><div style={{fontSize:9,color:C.dim}}>One public identity · one governed relationship field</div></div></header><div style={{display:'flex',gap:5,borderBottom:`1px solid ${C.border}`,paddingBottom:7,marginBottom:14}}>{([['field','NovaNet'],['nodes','Find Nodes'],['reasomate','ReasoMate']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{...btn(id===tab?C.teal:C.dim),background:id===tab?'rgba(0,212,170,.1)':'transparent'}}>{label}</button>)}</div>{tab==='field'&&<div style={{maxWidth:720,margin:'0 auto'}}><Composer token={token} profile={profile} onCreated={p=>setPosts(v=>[p,...v])}/>{posts.map(p=><PostCard key={p.id} post={p} token={token} myUid={profile?.uid||user?.uid||''} nodesByUid={byUid} onChange={next=>setPosts(v=>next?v.map(x=>x.id===next.id?next:x):v.filter(x=>x.id!==p.id))}/>)}</div>}{tab==='nodes'&&<NodesTab token={token} onOpen={n=>{setSelected(n);setTab('reasomate')}}/>}{tab==='reasomate'&&<ReasoMateTab token={token} myUid={profile?.uid||user?.uid||''} onFind={()=>setTab('nodes')}/>} {selected&&tab==='reasomate'&&<div style={{position:'fixed',inset:0,zIndex:40,background:'rgba(0,0,0,.55)',display:'grid',placeItems:'center',padding:20}} onClick={()=>setSelected(null)}><div style={{width:'min(430px,100%)'}} onClick={e=>e.stopPropagation()}><ProfileCardBridge node={selected} onClose={()=>setSelected(null)}/></div></div>}<footer style={{padding:'16px 0',textAlign:'center',color:C.dim,fontSize:9}}>Public identity is the bridge. Private memory remains private. Shared relational context comes from the existing ReasoMate thread.</footer></div>}

function ProfileCardBridge({node,onClose}:{node:NodeProfile;onClose:()=>void}){return <div style={{padding:16,background:C.card,border:`1px solid ${C.border}`,borderRadius:14}}><div style={{display:'flex',gap:11,alignItems:'center'}}><Avatar node={node} size={52}/><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600}}>{node.display_name}</div><div style={{fontSize:10,color:C.teal}}>{node.handle}</div></div></div>{node.bio&&<p style={{fontSize:11,color:C.muted,lineHeight:1.6}}>{node.bio}</p>}<button onClick={onClose} style={btn(C.blue)}>Close</button></div>}
