import React, { useEffect, useState } from 'react'
import { useAuth } from '../contexts/AuthContext'
import MarkdownViewer from '../components/MarkdownViewer'
import { formatToArkadiaMarkdown } from '../lib/arkadiaFormatter'

const API_BASE = (import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/$/, '')
const C = { teal:'#00D4AA', blue:'#6A9FD8', gold:'#C9A84C', red:'#C84848', text:'rgba(232,232,232,.9)', dim:'rgba(232,232,232,.35)', card:'rgba(14,17,32,.78)', border:'rgba(106,159,216,.14)' }

type Node = { username?:string|null; handle?:string|null; display_name:string; bio?:string|null; avatar_url?:string|null }
type Post = { id:string; owner_uid?:string; author:any; content:string; timestamp:number; edited_at?:number }
type Msg = { id:string; sender_uid:string; recipient_uid:string; content:string; timestamp:number }
const ago=(ts:number)=>{const d=Date.now()-ts;if(d<60000)return'now';if(d<3600000)return`${Math.floor(d/60000)}m`;if(d<86400000)return`${Math.floor(d/3600000)}h`;return`${Math.floor(d/86400000)}d`}
const btn=(color:string,disabled=false):React.CSSProperties=>({padding:'7px 11px',background:`${color}10`,border:`1px solid ${color}35`,borderRadius:8,color:disabled?C.dim:color,cursor:disabled?'not-allowed':'pointer',fontSize:9,letterSpacing:'.1em',textTransform:'uppercase'})

function Avatar({node,size=38}:{node:Node|any;size?:number}){return node?.avatar_url?<img src={node.avatar_url} alt="" style={{width:size,height:size,borderRadius:'50%',objectFit:'cover',border:`1px solid ${C.teal}35`}}/>:<div style={{width:size,height:size,borderRadius:'50%',display:'grid',placeItems:'center',background:'rgba(0,212,170,.08)',border:`1px solid ${C.teal}25`,color:C.teal,fontWeight:700}}>{node?.display_name?.slice(0,1).toUpperCase()||node?.avatar||'N'}</div>}

function Composer({token,profile,onCreated}:{token:string;profile:any;onCreated:(p:Post)=>void}){const[text,setText]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{if(!text.trim()||busy)return;setBusy(true);try{const r=await fetch(`${API_BASE}/api/transmissions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content:formatToArkadiaMarkdown(text),author:{name:profile?.display_name||'Node',avatar:profile?.role_sigil||'◈',role:profile?.role||'Node'}})});if(r.ok){const d=await r.json();onCreated(d.transmission);setText('')}}finally{setBusy(false)}};return <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:12,padding:13,marginBottom:12}}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Transmit something to the field…" rows={3} style={{width:'100%',boxSizing:'border-box',background:'rgba(0,0,0,.22)',border:'1px solid rgba(255,255,255,.07)',borderRadius:9,padding:10,color:C.text,resize:'vertical',outline:'none'}}/><div style={{display:'flex',justifyContent:'flex-end',marginTop:7}}><button onClick={submit} disabled={!text.trim()||busy} style={btn(C.teal,!text.trim()||busy)}>{busy?'Transmitting…':'Transmit'}</button></div></div>}

function PostCard({post,token,myUid,onChange}:{post:Post;token:string;myUid:string;onChange:(p:Post|null)=>void}){const[editing,setEditing]=useState(false);const[draft,setDraft]=useState(post.content);const[busy,setBusy]=useState(false);const own=post.owner_uid===myUid;const save=async()=>{if(!draft.trim()||busy)return;setBusy(true);try{const r=await fetch(`${API_BASE}/api/transmissions/${post.id}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content:draft.trim()})});if(r.ok){const d=await r.json();onChange(d.transmission);setEditing(false)}}finally{setBusy(false)}};const remove=async()=>{if(busy||!confirm('Delete this transmission?'))return;setBusy(true);try{const r=await fetch(`${API_BASE}/api/transmissions/${post.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`});if(r.ok)onChange(null)}finally{setBusy(false)}};return <article style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:12,overflow:'hidden',marginBottom:10}}><div style={{padding:12,display:'flex',alignItems:'center',gap:9}}><Avatar node={{display_name:post.author?.name,avatar:post.author?.avatar}}/><div style={{flex:1}}><div style={{color:C.text,fontSize:12,fontWeight:600}}>{post.author?.name||'Node'}</div><div style={{color:C.dim,fontSize:9}}>{post.author?.role||'Node'} · {ago(post.timestamp)}{post.edited_at?' · edited':''}</div></div>{own&&<div style={{display:'flex',gap:5}}><button onClick={()=>{setDraft(post.content);setEditing(v=>!v)}} style={btn(C.blue)}>Edit</button><button onClick={remove} disabled={busy} style={btn(C.red,busy)}>Delete</button></div>}</div><div style={{padding:'0 13px 13px'}}>{editing?<><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={5} style={{width:'100%',boxSizing:'border-box',background:'rgba(0,0,0,.2)',border:`1px solid ${C.blue}30`,borderRadius:9,color:C.text,padding:10}}/><div style={{display:'flex',justifyContent:'flex-end',gap:5,marginTop:6}}><button onClick={()=>setEditing(false)} style={btn(C.dim)}>Cancel</button><button onClick={save} disabled={busy} style={btn(C.teal,busy)}>Save</button></div></>:<MarkdownViewer content={post.content} compact/>}</div></article>}

function Messenger({token,profile}:{token:string;profile:any}){const[nodes,setNodes]=useState<Node[]>([]);const[q,setQ]=useState('');const[active,setActive]=useState<Node|null>(null);const[peerUid,setPeerUid]=useState('');const[messages,setMessages]=useState<Msg[]>([]);const[text,setText]=useState('');const[context,setContext]=useState<any>(null);const[busy,setBusy]=useState(false)
  const discover=async()=>{setBusy(true);try{const r=await fetch(`${API_BASE}/api/social/nodes?q=${encodeURIComponent(q)}`,{headers:{Authorization:`Bearer ${token}`}});if(r.ok)setNodes((await r.json()).nodes||[])}finally{setBusy(false)}}
  useEffect(()=>{discover()},[])
  const open=(node:Node)=>{setActive(node);setPeerUid('');setMessages([]);setContext(null)}
  const send=async()=>{const content=text.trim();const handle=(active?.username||active?.handle||'').replace(/^@/,'');if(!content||!handle)return;setBusy(true);try{const r=await fetch(`${API_BASE}/api/messages`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({recipient_handle:handle,content})});const d=await r.json();if(r.ok){const msg=d.message as Msg;setPeerUid(msg.recipient_uid);setMessages(v=>[...v,msg]);setText('');const c=await fetch(`${API_BASE}/api/relationships/${msg.recipient_uid}/context`,{headers:{Authorization:`Bearer ${token}`}});if(c.ok)setContext(await c.json())}}finally{setBusy(false)}}
  useEffect(()=>{if(!peerUid)return;Promise.all([fetch(`${API_BASE}/api/messages/thread/${peerUid}`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API_BASE}/api/relationships/${peerUid}/context`,{headers:{Authorization:`Bearer ${token}`}})]).then(async([m,c])=>{if(m.ok)setMessages((await m.json()).messages||[]);if(c.ok)setContext(await c.json())}).catch(()=>{})},[peerUid,token])
  return <div style={{display:'grid',gridTemplateColumns:'minmax(220px,.7fr) minmax(280px,1.3fr)',minHeight:520,border:`1px solid ${C.border}`,borderRadius:12,overflow:'hidden'}}><section style={{padding:12,borderRight:`1px solid ${C.border}`}}><div style={{display:'flex',gap:6,marginBottom:10}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&discover()} placeholder="Find a Node…" style={{flex:1,padding:9,background:'rgba(0,0,0,.2)',border:`1px solid ${C.border}`,borderRadius:8,color:C.text,outline:'none'}}/><button onClick={discover} style={btn(C.blue,busy)}>Find</button></div>{nodes.map((n,i)=><button key={n.username||n.handle||i} onClick={()=>open(n)} style={{width:'100%',display:'flex',gap:8,alignItems:'center',textAlign:'left',padding:9,marginBottom:6,background:active?.username===n.username?'rgba(0,212,170,.07)':C.card,border:`1px solid ${C.border}`,borderRadius:9,color:C.text,cursor:'pointer'}}><Avatar node={n} size={32}/><span><b style={{display:'block',fontSize:11}}>{n.display_name}</b><small style={{color:C.teal}}>{n.handle||'@node'}</small></span></button>)}</section><section style={{display:'flex',flexDirection:'column'}}>{!active?<div style={{flex:1,display:'grid',placeItems:'center',padding:30,textAlign:'center',color:C.dim}}>Find a Node to open a private ReasoMate thread.</div>:<><div style={{padding:12,borderBottom:`1px solid ${C.border}`,display:'flex',gap:9,alignItems:'center'}}><Avatar node={active} size={40}/><div><b style={{fontSize:12}}>{active.display_name}</b><div style={{color:C.teal,fontSize:9}}>{active.handle}</div></div></div><div style={{padding:'7px 12px',color:C.dim,fontSize:9}}>{context?.relationship?.interaction_count||0} shared messages · companion context derives from this thread</div><div style={{flex:1,overflowY:'auto',padding:12}}>{messages.map(m=><div key={m.id} style={{display:'flex',justifyContent:m.sender_uid===profile?.uid?'flex-end':'flex-start',marginBottom:7}}><div style={{maxWidth:'78%',padding:'8px 11px',background:m.sender_uid===profile?.uid?'rgba(0,212,170,.12)':'rgba(255,255,255,.05)',borderRadius:12,color:C.text,fontSize:11}}>{m.content}<div style={{color:C.dim,fontSize:8,marginTop:3}}>{ago(m.timestamp)}</div></div></div>)}</div><div style={{padding:10,borderTop:`1px solid ${C.border}`,display:'flex',gap:6}}><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={`Message ${active.display_name}…`} style={{flex:1,padding:9,borderRadius:18,background:'rgba(0,0,0,.2)',border:`1px solid ${C.border}`,color:C.text,outline:'none'}}/><button onClick={send} disabled={busy||!text.trim()} style={btn(C.teal,busy||!text.trim())}>Send</button></div></>}</section></div>}

export default function SocialFieldFinal(){const{isAuthenticated,profile,user}=useAuth();const token=user?.idToken||'';const[mode,setMode]=useState<'field'|'reasomate'>('field');const[posts,setPosts]=useState<Post[]>([]);useEffect(()=>{fetch(`${API_BASE}/api/transmissions`).then(r=>r.json()).then(d=>setPosts(d.transmissions||[])).catch(()=>{})},[]);if(!isAuthenticated)return <div style={{padding:40,textAlign:'center',color:C.dim}}>Sign in to enter the Social Identity + ReasoMate Field.</div>;return <div style={{minHeight:'calc(100vh - 80px)',color:C.text}}><header style={{display:'flex',alignItems:'center',gap:10,marginBottom:14}}><span style={{color:C.blue,fontSize:20}}>◉</span><div><h2 style={{margin:0,fontFamily:'Cinzel,serif',fontSize:20}}>The Social Field</h2><div style={{color:C.dim,fontSize:9}}>One public identity · one governed relationship field</div></div><div style={{marginLeft:'auto',display:'flex',gap:5}}><button onClick={()=>setMode('field')} style={btn(mode==='field'?C.teal:C.dim)}>NovaNet</button><button onClick={()=>setMode('reasomate')} style={btn(mode==='reasomate'?C.blue:C.dim)}>ReasoMate</button></div></header>{mode==='field'?<div style={{maxWidth:720,margin:'0 auto'}}><Composer token={token} profile={profile} onCreated={p=>setPosts(v=>[p,...v])}/>{posts.map(p=><PostCard key={p.id} post={p} token={token} myUid={profile?.uid||''} onChange={next=>setPosts(v=>next?v.map(x=>x.id===next.id?next:x):v.filter(x=>x.id!==p.id))}/>)}</div>:<Messenger token={token} profile={profile}/>}<footer style={{padding:'14px 0',color:C.dim,fontSize:9,textAlign:'center'}}>Public profile is the bridge. Private memory remains private. Shared relational context comes from the existing ReasoMate thread.</footer></div>}
