import React from 'react';
import { useAuth } from '../contexts/AuthContext';

type View = string;
type Props = { currentView: View; onNavigate: (view: View) => void; children: React.ReactNode };
const SURFACES=[{key:'novanet',label:'NovaNet',sub:'Nexus Hub',sigil:'◉',tone:'#6A9FD8'},{key:'sci',label:'SCI',sub:'Command',sigil:'⌘',tone:'#B08DE8'},{key:'solspire',label:'SolSpire',sub:'Private workspace',sigil:'◉',tone:'#C9A84C'},{key:'commune',label:'Oracle',sub:'ARKANA · Think',sigil:'✧',tone:'#00D4AA'}] as const;
const LENSES=[{key:'account',label:'Profile & Account',sigil:'P',tone:'#00D4AA'},{key:'grove',label:'Spiral Grove',sigil:'🌿',tone:'#00D4AA'},{key:'larder',label:'Living Larder',sigil:'🌾',tone:'#4CAF50'},{key:'offerings',label:'Offerings',sigil:'✦',tone:'#00D4AA'}] as const;
function activeSurfaceFor(v:View){if(v==='novanet')return'novanet';if(v==='sci')return'sci';if(v==='solspire'||v==='loops'||v==='codex'||v==='personal-echofeild'||v==='echofeild-matrix'||v==='spiral-codex')return'solspire';if(v==='commune'||v==='reasomate')return'commune';return null;}
function SurfaceButton({active,label,sub,sigil,tone,onClick}:{active:boolean;label:string;sub:string;sigil:string;tone:string;onClick:()=>void}){return <button type="button" onClick={onClick} aria-current={active?'page':undefined} style={{flexShrink:0,display:'flex',alignItems:'center',gap:8,padding:'9px 14px',background:active?`${tone}10`:'rgba(255,255,255,.012)',border:active?`1px solid ${tone}45`:'1px solid rgba(255,255,255,.055)',borderRadius:11,cursor:'pointer',transition:'all .18s'}}><span style={{fontSize:13}}>{sigil}</span><div style={{textAlign:'left'}}><p style={{fontFamily:'Inter,system-ui,sans-serif',fontSize:9,letterSpacing:'.14em',textTransform:'uppercase',color:active?tone:'rgba(232,232,232,.5)',margin:0,fontWeight:active?600:400}}>{label}</p><p style={{fontFamily:'Inter,system-ui,sans-serif',fontSize:8,color:active?`${tone}70`:'rgba(232,232,232,.24)',margin:0,whiteSpace:'nowrap'}}>{sub}</p></div></button>}
export default function PrismInteriorShell({currentView,onNavigate,children}:Props){
 const {user,profile,identitySpine,codex,isAuthenticated}=useAuth(); if(!isAuthenticated)return <>{children}</>;
 // SolSpire owns its complete workspace chrome. Private Codex/EchoField routes are compatibility aliases, never global surfaces.
 if(currentView==='solspire'||currentView==='loops'||currentView==='codex'||currentView==='personal-echofeild'||currentView==='echofeild-matrix'||currentView==='spiral-codex')return <>{children}</>;
 const displayName=identitySpine?.identity.preferred_name||profile?.display_name||user?.displayName||user?.email?.split('@')[0]||'Authenticated node'; const role=identitySpine?.identity.role||profile?.role||'Authenticated node'; const username=identitySpine?.identity.username?`@${identitySpine.identity.username}`:''; const sigil=identitySpine?.seed?.sigil||identitySpine?.symbolic?.sigil_seed||profile?.role_sigil||'◈'; const nodeKey=profile?.node_key||codex?.node_key||'private field'; const activeSurface=activeSurfaceFor(currentView);
 return <div data-testid="prism-interior-shell" style={{minHeight:'100vh',background:'#0C0D18',color:'#E9E7DF'}}><header style={{position:'sticky',top:0,zIndex:30,borderBottom:'1px solid rgba(255,255,255,.07)',background:'rgba(8,9,17,.94)',backdropFilter:'blur(22px)',WebkitBackdropFilter:'blur(22px)'}}><div style={{maxWidth:1180,margin:'0 auto',padding:'11px 16px 9px'}}><div style={{display:'flex',alignItems:'center',gap:10}}>{profile?.avatar_url?<img src={profile.avatar_url} alt="" style={{width:30,height:30,borderRadius:10,objectFit:'cover',border:'1px solid rgba(201,168,76,.25)'}}/>:<div style={{width:30,height:30,borderRadius:10,display:'grid',placeItems:'center',background:'rgba(201,168,76,.07)',border:'1px solid rgba(201,168,76,.24)',color:'#C9A84C',fontFamily:'Georgia,serif'}}>{sigil}</div>}<div style={{minWidth:0,flex:1}}><div style={{display:'flex',gap:8,alignItems:'baseline'}}><span style={{font:'600 10px Inter,system-ui,sans-serif',letterSpacing:'.12em',textTransform:'uppercase'}}>{displayName}</span><span style={{font:'8px Inter,system-ui,sans-serif',color:'rgba(233,231,223,.28)'}}>{role}</span>{username&&<span style={{font:'8px ui-monospace,monospace',color:'rgba(201,168,76,.45)'}}>{username}</span>}</div><div style={{font:'7px ui-monospace,monospace',color:'rgba(233,231,223,.2)',marginTop:2}}>{nodeKey}</div></div><div style={{font:'7px ui-monospace,monospace',letterSpacing:'.16em',textTransform:'uppercase',color:'rgba(0,212,170,.55)'}}>PRISM · AUTHENTICATED</div></div><div style={{display:'flex',gap:4,overflowX:'auto',paddingTop:10}}>{SURFACES.map(s=><SurfaceButton key={s.key} active={activeSurface===s.key} label={s.label} sub={s.sub} sigil={s.sigil} tone={s.tone} onClick={()=>onNavigate(s.key)}/>)}<button type="button" onClick={()=>onNavigate('account')} style={{flexShrink:0,padding:'9px 14px',borderRadius:11,border:'1px solid rgba(255,255,255,.055)',background:'rgba(255,255,255,.012)',color:'rgba(232,232,232,.55)',font:'9px Inter,system-ui,sans-serif',letterSpacing:'.14em',textTransform:'uppercase',cursor:'pointer'}}>Account</button></div></div></header><main>{children}</main></div>;
}