// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/arkadia-directions/AncientLight.tsx": () => import("../components/mockups/arkadia-directions/AncientLight.tsx"),
  "./components/mockups/arkadia-directions/CrystalRadiance.tsx": () => import("../components/mockups/arkadia-directions/CrystalRadiance.tsx"),
  "./components/mockups/arkadia-directions/SolarPrism.tsx": () => import("../components/mockups/arkadia-directions/SolarPrism.tsx")
};
