import React, { useEffect, useMemo, useState } from 'react';
import './solspire.css';
import ArkanaCommune from '../ArkanaCommune';
import ProjectDashboard from '../../pages/ProjectDashboard';
import type { Project } from '../../pages/ProjectDashboard';
import Overview from '../../pages/dashboard/Overview';
import KnowledgeOSPage from '../../pages/knowledge/KnowledgeOSPage';
import SettingsPage from '../../pages/SettingsPage';
import SourceSyncPanel from './SourceSyncPanel';
import { CommercialPanel, Observatory, WeaverSummary, WorkspaceCollection, WorkspaceFiles } from '../../pages/SolSpireWorkspacePanels';
import type { WorkspaceCollectionKind } from '../../pages/SolSpireWorkspacePanels';
import { search as searchKnowledge, setKnowledgeAuthToken } from '../../lib/knowledgeApi';
import { useAuth } from '../../contexts/AuthContext';

export type SolSpireLens = 'overview'|'commercial'|'knowledge'|'files'|'conversations'|'tasks'|'memory'|'weaver'|'observatory'|'settings';
type NavItem = { id: SolSpireLens; label: string; sigil: string; accent: string; question: string };
const NAV: NavItem[] = [
  {id:'overview',label:'Overview',sigil:'◎',accent:'#6A9FD8',question:'What matters now?'},
  {id:'commercial',label:'Commercial',sigil:'◈',accent:'#C9A84C',question:'Where is value emerging?'},
  {id:'knowledge',label:'Knowledge',sigil:'◉',accent:'#00D4AA',question:'What does the system know?'},
  {id:'files',label:'Files',sigil:'◫',accent:'#C9A84C',question:'What exists?'},
  {id:'conversations',label:'Conversations',sigil:'◌',accent:'#6A9FD8',question:'What am I thinking through?'},
  {id:'tasks',label:'Tasks',sigil:'□',accent:'#00D4AA',question:'What commitments are active?'},
  {id:'memory',label:'Memory',sigil:'∞',accent:'#B08DE8',question:'What persists?'},
  {id:'weaver',label:'Weaver',sigil:'⚒',accent:'#B08DE8',question:'What is being worked on?'},
  {id:'observatory',label:'Observatory',sigil:'⟐',accent:'#6A9FD8',question:'What happened?'},
  {id:'settings',label:'Settings',sigil:'◆',accent:'#9A9AA2',question:'How does the environment behave?'},
];

export type SolSpireObject = { id:string; type:string; title:string; summary?:string; status?:string; projectId?:string; source?:string; updatedAt?:string|number };
export type SolSpireRelation = { type:'CONNECTED TO'|'DERIVED FROM'|'REFERENCES'|'BELONGS TO'|'FOLLOW-UP FOR'|'GENERATED FROM'; sourceId:string; targetId:string };
export function ObjectCard({object, accent='#C9A84C', onOpen}:{object:SolSpireObject; accent?:string; onOpen?:()=>void}) { return <article className="solspire-object" onClick={onOpen} role={onOpen?'button':undefined} tabIndex={onOpen?0:undefined} onKeyDown={e=>{if(onOpen&&(e.key==='Enter'||e.key===' '))onOpen()}}><div className="solspire-kicker" style={{color:`${accent}aa`}}>{object.type}</div><h3 className="solspire-title">{object.title}</h3>{object.summary&&<p className="solspire-object-summary">{object.summary}</p>}<div className="solspire-object-meta"><span>{object.status||'ACTIVE'}</span>{object.projectId&&<span>{object.projectId}</span>}</div><div className="solspire-id">{object.id}</div></article>; }
export function RelationChip({relation, label}:{relation:SolSpireRelation; label?:string}) { return <span className="solspire-relation" title={`${relation.type} ${relation.targetId}`}>{relation.type}{label?` · ${label}`:''}</span>; }
export function ActivityItem({type,title,context,time,id}:{type:string;title:string;context?:string;time?:string;id?:string}) { return <div className="solspire-activity-item"><span className="solspire-activity-dot"/><div><div className="solspire-kicker">{type}</div><div className="solspire-activity-title">{title}</div>{context&&<div className="solspire-activity-context">{context}</div>}</div><div className="solspire-activity-time">{time||''}{id&&<small>{id}</small>}</div></div>; }

function Header({identity,onSearch,onArkana,onMenu}:{identity:string;onSearch:()=>void;onArkana:()=>void;onMenu:()=>void}) { return <header className="solspire-canonical-header"><div className="solspire-brand"><span className="solspire-mark">◈</span><div><div className="solspire-brand-name">SOLSPIRE</div><div className="solspire-brand-sub">private contextual workspace</div></div></div><div className="solspire-header-actions"><button type="button" className="solspire-quiet-button" onClick={onSearch}>⌕ <span>Search</span></button><button type="button" className="solspire-arkana-button" onClick={onArkana}>⌁ <span>Ask Arkana</span></button><button type="button" className="solspire-menu-button" onClick={onMenu} aria-label="Open SolSpire navigation">☰</button><div className="solspire-identity"><span className="solspire-online-dot"/>{identity}</div></div></header>; }
function MobileNav({section,onSection,onMore}:{section:SolSpireLens;onSection:(s:SolSpireLens)=>void;onMore:()=>void}) { const mobile=[NAV[0],NAV[3],NAV[5],NAV[7],NAV[8]]; return <nav className="solspire-mobile-bottom">{mobile.map(n=><button key={n.id} type="button" className={section===n.id?'active':''} onClick={()=>onSection(n.id)}><span>{n.sigil}</span><small>{n.label}</small></button>)}<button type="button" onClick={onMore}><span>•••</span><small>More</small></button></nav>; }
function Sidebar({section,onSection}:{section:SolSpireLens;onSection:(s:SolSpireLens)=>void}) { return <aside className="solspire-sidebar"><div className="solspire-sidebar-intro"><span className="solspire-online-dot"/><span>AUTHENTICATED FIELD</span><small>one surface · private</small></div>{NAV.map(n=><button key={n.id} type="button" className={`solspire-nav-button ${section===n.id?'active':''}`} style={{'--lens-accent':n.accent} as React.CSSProperties} onClick={()=>onSection(n.id)}><span>{n.sigil}</span><div><strong>{n.label}</strong><small>{n.question}</small></div></button>)}</aside>; }
function ContextBar({lens,project,onArkana}:{lens:NavItem;project?:Project|null;onArkana:()=>void}) { return <div className="solspire-context-bar"><div><span className="solspire-mono">SOLSPIRE / {lens.label.toUpperCase()}</span>{project&&<><span className="solspire-context-separator">/</span><strong>{project.name}</strong></>}</div><button type="button" onClick={onArkana}>⌁ Ask Arkana {project?'about this context':'about this workspace'}</button></div>; }
function SearchOverlay({onClose}:{onClose:()=>void}) { const {user}=useAuth(); const [query,setQuery]=useState(''); const [results,setResults]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); useEffect(()=>{setKnowledgeAuthToken(user?.idToken??null);},[user?.idToken]); useEffect(()=>{if(!query.trim()){setResults([]);setError(null);return;}const timer=window.setTimeout(()=>{setLoading(true);setError(null);searchKnowledge(query.trim(),['semantic','fulltext','project','timeline'],12).then(r=>{const groups=['semantic','fulltext','project','timeline'];const flat=groups.flatMap(k=>(r as any)[k]||[]);const seen=new Set<string>();setResults(flat.filter((x:any)=>{const key=String(x.note_uuid||x.id||x.title||JSON.stringify(x));if(seen.has(key))return false;seen.add(key);return true;}));}).catch(e=>setError(e.message||'Search unavailable')).finally(()=>setLoading(false));},320);return()=>window.clearTimeout(timer)},[query]); return <div className="solspire-overlay" role="dialog" aria-modal="true"><div className="solspire-search-panel"><div className="solspire-overlay-head"><div><span className="solspire-kicker">Universal search</span><h2>Search SolSpire</h2></div><button type="button" onClick={onClose}>×</button></div><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search files, knowledge, conversations, tasks, memory…" />{loading&&<div className="solspire-search-state">Searching Knowledge OS…</div>}{error&&<div className="solspire-search-error">{error}</div>}{!loading&&query.trim()&&!results.length&&!error&&<div className="solspire-search-state">No matching objects found.</div>}<div className="solspire-search-results">{results.map((x:any,i)=><article key={`${x.note_uuid||x.id||i}`}><div className="solspire-kicker">{x.note_type||x.type||'KNOWLEDGE'}</div><h3>{x.title||x.name||'Untitled object'}</h3><p>{String(x.content||x.summary||'').slice(0,220)}</p><span>{x.note_uuid||x.id||''}</span></article>)}</div><div className="solspire-search-hint">Semantic and full-text search are backed by the existing Knowledge OS. No parallel search index is created here.</div></div></div>; }
function ArkanaOverlay({context,onClose}:{context:string;onClose:()=>void}) { return <div className="solspire-overlay" role="dialog" aria-modal="true"><div className="solspire-arkana-panel"><div className="solspire-overlay-head"><div><div className="solspire-kicker">Contextual intelligence</div><h2>Ask Arkana</h2><p>{context}</p></div><button type="button" onClick={onClose}>×</button></div><ArkanaCommune initialMessage={`You are being invoked from SolSpire. Current workspace context: ${context}. Keep this context in view when interpreting the user's request. Do not imply autonomous authority; proposals remain subject to human decision.`}/></div></div>; }
function LensContent({section,onOpenProject}:{section:SolSpireLens;onOpenProject:(p:Project)=>void}) { if(section==='overview')return <><Overview/><div className="solspire-attention-note"><div className="solspire-kicker">Experience grammar</div><h3>One field, many lenses.</h3><p>Projects, files, conversations, tasks, memory, knowledge and governed work remain existing capabilities. This lens is for situational awareness, not another dashboard kingdom.</p></div></>; if(section==='commercial')return <CommercialPanel/>; if(section==='knowledge')return <KnowledgeOSPage/>; if(section==='files')return <WorkspaceFiles onOpenProject={onOpenProject}/>; if(section==='conversations'||section==='tasks'||section==='memory')return <WorkspaceCollection kind={section as WorkspaceCollectionKind}/>; if(section==='weaver')return <WeaverSummary onOpenProject={onOpenProject}/>; if(section==='observatory')return <Observatory/>; return <><SettingsPage/><SourceSyncPanel/></>; }

export default function SolSpireExperience({identity='Authenticated node',initialSection='overview'}:{identity?:string;initialSection?:SolSpireLens}) { const [section,setSection]=useState<SolSpireLens>(initialSection); const [project,setProject]=useState<Project|null>(null); const [search,setSearch]=useState(false); const [arkana,setArkana]=useState(false); const [more,setMore]=useState(false); const lens=useMemo(()=>NAV.find(n=>n.id===section)||NAV[0],[section]); const context=project?`${project.name} project context · files, conversations, tasks, memory, knowledge and governed Weaver work`:`${lens.label} lens · authenticated SolSpire workspace state`;
  useEffect(()=>{setSection(initialSection);setProject(null);},[initialSection]);
  const selectSection=(next:SolSpireLens)=>{setSection(next);setProject(null);const path=next==='overview'?'/solspire':`/solspire/${next}`;if(window.location.pathname!==path)window.history.pushState({},'',path);};
  if(project)return <div className="solspire-workspace"><Header identity={identity} onSearch={()=>setSearch(true)} onArkana={()=>setArkana(true)} onMenu={()=>setMore(true)}/><div className="solspire-project-context"><button type="button" onClick={()=>setProject(null)}>← Files</button><div><span className="solspire-kicker">PROJECT CONTEXT</span><strong>{project.name}</strong></div><span className="solspire-mono">same SolSpire · deeper context</span></div><ProjectDashboard project={project} onBack={()=>setProject(null)} onProjectUpdated={setProject}/>{search&&<SearchOverlay onClose={()=>setSearch(false)}/>} {arkana&&<ArkanaOverlay context={context} onClose={()=>setArkana(false)}/>} {more&&<div className="solspire-mobile-menu">{NAV.map(n=><button key={n.id} onClick={()=>{selectSection(n.id);setMore(false)}}>{n.sigil} <span>{n.label}</span><small>{n.question}</small></button>)}</div>}</div>;
  return <div className="solspire-workspace"><Header identity={identity} onSearch={()=>setSearch(true)} onArkana={()=>setArkana(true)} onMenu={()=>setMore(true)}/><div className="solspire-body"><Sidebar section={section} onSection={selectSection}/><main className="solspire-main"><ContextBar lens={lens} onArkana={()=>setArkana(true)}/><div className="solspire-lens-heading"><div><span className="solspire-lens-sigil" style={{color:lens.accent}}>{lens.sigil}</span><div><div className="solspire-kicker">{lens.question}</div><h1>{lens.label}</h1></div></div><div className="solspire-lens-actions"><button type="button" onClick={()=>setSearch(true)}>⌕ Search</button><button type="button" onClick={()=>setArkana(true)}>⌁ Arkana</button></div></div><div className="solspire-divider"/><section className="solspire-content"><LensContent section={section} onOpenProject={setProject}/></section></main></div><MobileNav section={section} onSection={selectSection} onMore={()=>setMore(true)}/>{search&&<SearchOverlay onClose={()=>setSearch(false)}/>} {arkana&&<ArkanaOverlay context={context} onClose={()=>setArkana(false)}/>} {more&&<div className="solspire-mobile-menu">{NAV.map(n=><button key={n.id} onClick={()=>{selectSection(n.id);setMore(false)}}>{n.sigil} <span>{n.label}</span><small>{n.question}</small></button>)}</div>}</div>;
}
